#pragma once
#include <cstdlib>
#include <utility>
#include <memory>
#include <concepts>
#include <optional>
#include <variant>
#include <tuple>
#include <array>
#include <initializer_list>
#include <vector>
#include <deque>
#include <list>
#include <set>
#include <map>
#include <stack>
#include <queue>
#include <algorithm>
#include <ranges>
#include <iterator>
#include <string>
#include <string_view>
#include <iostream>
#include <sstream>
#include <fstream>
#include <filesystem>
#include <functional>
#include <locale>
#include <codecvt>
