.Dd April 19, 2026
.Dt TUR 1
.Os
.Sh NAME
.Nm tur
.Nd compose Turing machines
.Sh SYNOPSIS
.Nm tur
.Op Fl c
.Op Fl iIO
.Oo
.Fl b
.Ar path
.Oc
.Oo
.Fl x
.Ar suffix
.Oc
.Oo
.Fl m
.Ar machine1.tm
.Fl m
.Ar machine2.tm Ns \&...
.Oc
.Op Ar source.tur
.Op Ar machine.tm
.Nm tur
.Fl r
.Op Fl denskC
.Ar machine.tm
.Nm tur
.Fl cr
.Op Fl iOenskC
.Oo
.Fl b
.Ar path
.Oc
.Oo
.Fl x
.Ar suffix
.Oc
.Oo
.Fl m
.Ar machine1.tm
.Fl m
.Ar machine2.tm Ns \&...
.Oc
.Ar source.tur
.Sh DESCRIPTION
.Nm
compiles a description of a Turing machine given in the
.Ar source
file (conventionaly named with a
.Sq tur
suffix)
into an actual Turing machine,
i.e. the tuples describing the machine\(cqs transfer function
and stores it in the
.Ar machine
output file (conventionaly named with a
.Sq tm
suffix).
.Pp
The source language is described below.
It is expressive enough to describe compositions
of complex machines from simpler machines.
.Pp
The
.Fl c
and
.Fl r
options determine what to do.
If neither on them is present,
.Fl c
is assumed.
.Bl -tag -width Ds
.It Fl c , Fl \-compile
Compile the machine from source.
The source is read from the
.Ar source
file or from the standard input if no source file is specified.
The resulting machine is saved in the
.Ar machine
output file or printed to the standard output if no output file is specified.
.It Fl r , Fl \-run
Run the resulting machine.
Exactly one argument is required: the
.Ar machine
file from which the machine transfer function is read
or (when used with the
.Fl c
option) the
.Ar source
file from which the machine is compiled first.
The initial content of the tape is read from the standard input;
the eventual content of the tape is printed to the standard output,
if and when the machine halts.
.El
.Pp
The following options can be used with the
.Fl c
option:
.Bl -tag -width Ds
.It Fl i , Fl \-instructions
Print the instructions (intermediate representation of the program)
to the standard error output.
.It Fl I , Fl \-only-instructions
Do not create the machine, only display the instructions.
These are printed into the output file or to the standard output
if no output file is specified.
.It Fl O , Fl \-optimize
Optimize the machine.
.It Fl b Pa path , Fl \-include-base Pa path
Use this
.Pa path
as the base path for
.Ic include
statements in the source.
The default path is the directory where the
.Ar source
file is located.
.It Fl x Ar suffix , Fl \-include-suffix Ar suffix
Use this string as the suffix of included files.
The default is
.Em .tm .
The suffix does not have to be just an extension, the directory
separator can be used to mark that the machine file is inside a
directory with the name of the include.
.It Fl m Ar machine1.tm , Fl \-machine Ar machine1.tm
Use this machine for
.Ic require
statements in the program.
Machines provided with this option map in order with
.Ic require
statements.
.El
.Pp
The following options can be used with the
.Fl r
option:
.Bl -tag -width Ds
.It Fl s , Fl \-steps
Trace the machine steps: print the tape content and the current state
to the standard error output.
.It Fl k , Fl \-keep-blanks
Keep leading and trailing blank symbols.
.It Fl d , Fl \-decode
Decode sequences of ones in the output as decimal numbers.
.It Fl e , Fl \-encode
Encode numbers from the input as sequences of ones (unary notation).
.It Fl n , Fl \-numbers
A shortcut for
.Fl d Fl e .
.It Fl C , Fl \-no-color
Do not highlight the current position in the output or while tracing with
formating sequences.
Normally, when tracing or when the output is printed
without encoding, the current position is highlighted, which may pose a
problem when using this output further.
.El
.Ss The Source Language
The source language is a high-order language, described below in detail.
As an example, the following source get compiled into a machine
that computes the greatest common divisor of two given numbers:
.Bd -literal
	[a, b] = input;
	while b > 0:
		B = a mod b;
		a = b;
		b = B;
	endwhile;
	output = a;
.Ed
.Pp
Every
.Em variable
represents one tape of the machine on which numbers can be written.
The special names
.Va input
and
.Va output
are reserved for the input tape and the output tape.
.Pp
The following types of
.Em expressions
are supported:
.Bl -tag -width Ds
.It A numeric constant (any positive integer or zero):
.Bd -literal
0
18
.Ed
.It The number of items on the tape of a variable:
.Bd -literal
count variable
\(*r variable
.Ed
.It The value of a variable or a specific slice thereof:
.Bd -literal
input # The first number of a variable
input[0] # Also the first number
input[0:1] # Also the first number
input[4] # The fifth number
input[5:7] # The fifth and sixth number
input[1:] # All numbers except the first one
input[0:2] # First two numbers
input[:2] # Also first two numbers
input[0:] # All numbers
input[:] # Also all numbers
input... # Also all numbers (either three dots or the Unicode ellipsis, both is supported)
.Ed
.It The result of a machine on a given input (any non-logical expressions); the result can be sliced:
.Bd -literal
f() # The result of the run of f on an empty tape (first number)
f()... # The result of the run of f on an empty tape (the whole tape)
g(input[0], input[1])[1] # The second number of the run of the g machine with the first two numbers of the input
g(input[:2])[1] # The same thing
g(12, input)... # The whole result of running g on a tape with the number 12 and the first number of the input
h(g(f(input)...)...)... # Composition of three functions
.Ed
.It Arithmetical and logical operations:
.Bd -literal
a + b # Addition
a - b # Subtraction, both hyphen-minus and Unicode minus is supported
a \[u22C5] b # Multiplication (Unicode dot operator)
a \[tmu] b # Also multiplication
a * b # Also multiplication
a / b # Integer division (undefined behavior for division by zero), both normal slash and Unicode fraction slash is supported
a \[u2236] b # Also division (Unicode ratio)
a mod b # Modulo (remainder; undefined behavior for division by zero)
a % b # Also modulo
a min b # Minumum of two values
a & b # Also minumum of two values
a max b # Maximum of two values
a | b # Also maximum of two values
a==b # Equality
a!=b # Inequality
a \(!= b # Also inequality
a < b # Less than
a > b # Greater than
a \*(<= b # Less than or equal
a <= b # Also less than or equal
a \*(>= b # Greater than or equal
a >= b # Also greater than or equal
!(a==b) # Negation
\[tno] a==b # Also negation
a==b \(AN c==d # Conjunction (and)
a==b && c==d # Also conjunction
a==b and c==d # Also conjunction
a==b \(OR c==d # Disjunction (or)
a==b || c==d # Also disjunction
a==b or c==d # Also disjunction
a==b xor c==d # Exclusive disjunction (xor)
.Ed
.El
.Pp
The following types of
.Em statements
are supported:
.Bl -tag -width Ds
.It A definition of a Turing machine:
.Bd -literal
dec1 = { A 1 0 R _ }; # old state, old symbol, new symbol, direction, new state
dec2 = { stateA 1 0 R stateB }; # Any state name is valid, if it does not contain a digit, a whitespace, } or #.
dec3 = { stateA10RstateB }; # The whitespace is optional (any number of spaces, tabs or newlines can be used).
inc1 = { A11LA A01N_ }; # More transitions (the old state of the first transitions is the initial state). This whitespace is not optional.
inc2 = { A11LA A01SB }; # _ had no special meaning, when the machine halts, the answer is read. S is an alias of N.
inc3 = {
	A 1 1 L A
	A 0 1 N _ # place one extra 1
}; # Using more lines and adding comments might improve legibility.
.Ed
.It \&An include of a machine defined in a separate file (the syntax of the machine file is the same as in the {} block):
.Bd -literal
include gcd; # gcd.tm is expected in the same directory as the source file, unless specified otherwise with CLI options.
.Ed
.It \&An include of a requried machine passed by a command line option at compile time:
.Bd -literal
require f; # Compilation requires an option like this: -m machine1.tm
require g; # More requirements require more -m options.
.Ed
.It Call of a Turing machine on a variable (a tape). Unlike call expressions, changes will affect the variable directly:
.Bd -literal
f(input...); # Using ... is required.
.Ed
.It Assignment of an expression to a variable, possibly at a given index:
.Bd -literal
output = 1; # The variable output will contain a single number 1.
output[2:] = 2; # The first two numbers will be preserved, 2 will rewrite the rest (undefined behavior for less than two numbers in output).
output[] = 3; # Append the number 3.
#output[4] = 4; # This is forbidden (for now), any destination slice must be rightwise unbounded. A workaround is: output[4:] = [4, output[5:]];
output = input; # Assign the first number of input.
output = input...; # Assign the whole content of input.
output[10:] = f(input[5:8])[2:4]; # Any non-logical expression of any length can be assigned.
output = output[1:5];
output[2:] = output[1:5];
.Ed
.It Incrementing or decrementating the first number on a tape:
.Bd -literal
a++;
b--; # Either two hyphen-minuses or two Unicode minuses.
.Ed
.It Branching ( Ic if , Ic else Ns ):
.Bd -literal
if input==42:
	output = 1;
else: # The else part is optional, endif can directly follow the first branch.
	output = 0;
endif;
.Ed
.It Loops ( Ic while , Ic loop Ns ):
.Bd -literal
loop: # Loop without condition (until break):
	while a > 0: # Loop with condition.
		if b==10:
			continue; # Skip to the next iteration of the innermost loop (the inner loop here).
		endif;
		a--;
	endwhile;
	b++;
	if a==10:
		break; # Exit the innermost loop (the outer loop here).
	endif;
endloop;
.Ed
.It Ic exit No statement :
.Bd -literal
if output==20:
	exit; # Skip behind the last statement of the program.
endif;
output = 40; # This will be skipped if the first number of the output is 20.
.Ed
.It Joining (imploding) multiple expressions to a varible:
.Bd -literal
output = [1, 2, 3]; # output will contain those three numbers.
output[2:] = [1, 2, 3]; # The variable can be indexed.
output[] = [1, 2, 3]; # Appending is also possible.
output = [f(input)..., 10, input[2:5], output]; # Any non-logical expressions can be used.
.Ed
.It Splitting (exploding) an expression to multiple variables:
.Bd -literal
[a, b, c] = input; # First number goes to a, second number goes to b, third number goes to c (undefined behavior for less than 3 numbers in input).
[a, b...] = input; # First number goes to a, the reset goes to b (undefined behavior for empty input). Only the last variable can have the ellipsis.
[a, b] = input...; # The ellipsis can be there, but it is optional.
[a, b] = a[1:]; # Other indexation than ellipsis is possible, but it has to be rightwise unbounded.
[a, b] = f(a, b)...; # Any expression which can yield more numbers is possible as the right side. The ellipsis is optional here as well.
.Ed
.El
.Sh AUTHORS
.An Šimon Rataj Aq Mt ratajs@ratajs.cz
.Pp
This software was developed with the support of the
Faculty of Information Technology, Czech Technical University in Prague.
For more information, visit
.Lk https://fit.cvut.cz .
