#include "./multiTapeMachineFactory.hpp"
#include "./singleTapeMachineFactory.hpp"
#include "../IO/unexpectedError.hpp"

/*!
 * The constructor of MultiTapeMachineFactory.
 * \param tapesCount Number of virtual tapes (excluding the special zeroth tape).
 */
MultiTapeMachineFactory::MultiTapeMachineFactory(size_t tapesCount): tapesCount(tapesCount) {};

/*!
 * Add one ‘transition’ in a multi-tape system.
 * \tparam symbol Old symbol on the tape.
 * \tparam symbol New symbol on the tape.
 * \tparam direction Direction of the transition (left or right).
 * \param state Start state of the transition, the current state if {}.
 * \param newState End state of the transition, a new state if {} (which shall then be the current state).
 * \param tape If non-zero, the machine is expected to be on that tape and the zeroth tape will be filled with zeros if necessary; otherwise, the zeroth tape is not heeded.
 */
template<bool symbol, bool newSymbol, Machine::Direction direction> requires (direction!=Machine::Direction::N)
	std::wstring MultiTapeMachineFactory::addSuperTransition(std::optional<std::wstring> state, std::optional<std::wstring> newState, size_t tape) {
		size_t tapesCount, x;

		tapesCount = (this->tapesCount + 1);
		this->addTransition<symbol, newSymbol, direction>(state, {});
		for(x = 1; x < tapesCount - 1; x++) {
			if((tape + x) % tapesCount==0) {
				this->addTransition<true, true, direction>({}, {});
				this->addTransition<false, true, direction>(this->generator.getLastState(), this->generator.getCurrentState());
			}
			else
				this->addTransition<direction>({}, {});
		};
		if((tape + x) % tapesCount==0) {
			if(newState) {
				this->addTransition<true, true, direction>({}, newState);
				this->addTransition<false, true, direction>({}, newState);
			}
			else {
				newState = this->addTransition<true, true, direction>({}, {});
				this->addTransition<false, true, direction>(this->generator.getLastState(), newState);
			};
		}
		else
			newState = this->addTransition<direction>({}, newState);

		return (*newState);
	};

/*!
 * Add one ‘transition’ in a multi-tape system (keeping the original symbol).
 * \tparam direction Direction of the transition (left or right).
 * \param state Start state of the transition, the current state if {}.
 * \param newState End state of the transition, a new state if {} (which shall then be the current state).
 * \param tape If non-zero, the machine is expected to be on that tape and the zeroth tape will be filled with zeros if necessary; otherwise, the zeroth tape is not heeded.
 */
template<Machine::Direction direction> requires (direction!=Machine::Direction::N)
	std::wstring MultiTapeMachineFactory::addSuperTransition(std::optional<std::wstring> state, std::optional<std::wstring> newState, size_t tape) {
		size_t tapesCount, x;

		tapesCount = (this->tapesCount + 1);
		this->addTransition<direction>(state, {});
		for(x = 1; x < tapesCount - 1; x++) {
			if((tape + x) % tapesCount==0) {
				this->addTransition<true, true, direction>({}, {});
				this->addTransition<false, true, direction>(this->generator.getLastState(), this->generator.getCurrentState());
			}
			else
				this->addTransition<direction>({}, {});
		};
		if((tape + x) % tapesCount==0) {
			newState = this->addTransition<true, true, direction>({}, newState);
			this->addTransition<false, true, direction>({}, newState);
		}
		else
			newState = this->addTransition<direction>({}, newState);

		return (*newState);
	};

/*!
 * This method goes to the first 1 of the zeroth tape.
 * \param returningState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tape If non-zero, it allows this tape to have one extra 1 one cell to the left of the beginning of the zeroth tape, it marks the cell on the zeroth tape in this case.
 */
std::wstring MultiTapeMachineFactory::goHome(std::optional<std::wstring> returningState, std::optional<std::wstring> endState, size_t tape) {
	size_t tapesCount, x;
	std::wstring repairingState, skippedRepairingState;

	tapesCount = (this->tapesCount + 1);

	if(!returningState)
		returningState = this->generator.getCurrentState();

	if(tape!=0) {
		this->generator.increment();
		repairingState = this->generator.getCurrentState();
	};

	this->addSuperTransition<true, true, Machine::Direction::L>(returningState, returningState); // 1

	this->addTransition<false, false, Machine::Direction::R>(returningState, {}); // 0
	for(x = 1; x < tapesCount - 1; x++) {
		if(x==tape)
			this->addTransition<true, true, Machine::Direction::N>({}, repairingState);
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	};

	if(tape==0) {
		endState = this->addTransition<false, false, Machine::Direction::R>({}, endState);

		return (*endState);
	};

	if(x==tape)
		this->addTransition<true, true, Machine::Direction::N>({}, repairingState);
	skippedRepairingState = this->addTransition<false, false, Machine::Direction::R>({}, {});

	this->addTransition<true, true, Machine::Direction::L>(repairingState, {});
	for(x = (tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	endState = this->addTransition<false, true, Machine::Direction::N>({}, endState);
	this->addTransition<true, true, Machine::Direction::N>(skippedRepairingState, endState);

	return (*endState);
};

/*!
 * This method finds the beginning of a tape.
 * It expects the head to be at the first 1 of the zeroth tape.
 * It stops at the first 1 of the specified tape.
 * \param tape The number of the tape.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param isEmptyTapeAllowed If false, the behavior with the specified tape being empty is undefined. If true and the tape is empty, it stops somewhere at a valid position on the tape (with 1 on the zeroth tape).
 */
std::wstring MultiTapeMachineFactory::findTape(size_t tape, std::optional<std::wstring> startState, std::optional<std::wstring> endState, bool isEmptyTapeAllowed) {
	size_t tapesCount, x;
	std::wstring findingBeginningState, emptyTapeState, emptyTapeEndState;

	tapesCount = (this->tapesCount + 1);

	if(!startState)
		startState = this->generator.getCurrentState();

	if(isEmptyTapeAllowed) {
		this->generator.increment();
		emptyTapeState = this->generator.getCurrentState();
	};

	this->addTransition<true, true, Machine::Direction::R>(startState, {});
	for(x = 1; x < tape; x++)
		this->addTransition<Machine::Direction::R>({}, {});

	findingBeginningState = this->generator.getCurrentState();

	this->addTransition<false, false, Machine::Direction::R>(findingBeginningState, {});
	for(x = 1; x < tapesCount - 1; x++) {
		if((tape + x) % tapesCount==0) {
			if(isEmptyTapeAllowed)
				this->addTransition<false, false, Machine::Direction::N>({}, emptyTapeState);
			this->addTransition<true, true, Machine::Direction::R>({}, {});
		}
		else
			this->addTransition<Machine::Direction::R>({}, {});
	};
	if((tape + x) % tapesCount==0) {
		if(isEmptyTapeAllowed)
			this->addTransition<false, false, Machine::Direction::N>({}, emptyTapeState);
		this->addTransition<true, true, Machine::Direction::R>({}, findingBeginningState);
	}
	else
		this->addTransition<Machine::Direction::R>({}, findingBeginningState);

	if(isEmptyTapeAllowed) {
		this->addSuperTransition<false, false, Machine::Direction::L>(emptyTapeState, {});
		this->goHome({}, {});
		this->addTransition<true, true, Machine::Direction::R>({}, {});
		for(x = 1; x < tape; x++)
			this->addTransition<Machine::Direction::R>({}, {});
		emptyTapeEndState = this->generator.getCurrentState();
	};

	endState = this->addTransition<true, true, Machine::Direction::N>(findingBeginningState, endState);
	if(isEmptyTapeAllowed)
		this->addTransition<false, false, Machine::Direction::N>(emptyTapeEndState, endState);

	return (*endState);
};

/*!
 * This method skips one number on the current tape.
 * \param skippingState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tape If non-zero, the method expects to start on this tape and the zeroth tape will be marked while skipping in case that this tape has something beyond the end of the zeroth tape.
 */
std::wstring MultiTapeMachineFactory::skipNumber(std::optional<std::wstring> skippingState, std::optional<std::wstring> endState, size_t tape) {
	size_t tapesCount, x;

	tapesCount = (this->tapesCount + 1);

	if(!skippingState)
		skippingState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::R>(skippingState, {}); // 1
	for(x = 1; x < tapesCount - 1; x++) {
		if((tape + x) % tapesCount==0) {
			this->addTransition<true, true, Machine::Direction::R>({}, {});
			this->addTransition<false, true, Machine::Direction::R>(this->generator.getLastState(), this->generator.getCurrentState());
		}
		else
			this->addTransition<Machine::Direction::R>({}, {});
	};
	if((tape + x) % tapesCount==0) {
		this->addTransition<true, true, Machine::Direction::R>({}, skippingState);
		this->addTransition<false, true, Machine::Direction::R>({}, skippingState);
	}
	else
		this->addTransition<Machine::Direction::R>({}, skippingState);

	this->addTransition<false, false, Machine::Direction::R>(skippingState, {}); // 0
	for(x = 1; x < tapesCount - 1; x++) {
		if((tape + x) % tapesCount==0) {
			this->addTransition<true, true, Machine::Direction::R>({}, {});
			this->addTransition<false, true, Machine::Direction::R>(this->generator.getLastState(), this->generator.getCurrentState());
		}
		else
			this->addTransition<Machine::Direction::R>({}, {});
	};
	if((tape + x) % tapesCount==0) {
		if(!endState) {
			endState = this->addTransition<true, true, Machine::Direction::R>({}, {});
			this->addTransition<false, true, Machine::Direction::R>(this->generator.getLastState(), endState);
		}
		else {
			this->addTransition<true, true, Machine::Direction::R>({}, endState);
			this->addTransition<false, true, Machine::Direction::R>({}, endState);
		};
	}
	else
		endState = this->addTransition<Machine::Direction::R>({}, endState);

	return (*endState);
};

/*!
 * This method clears one number on any tape.
 * It stops on the next number (or where the next number would be).
 * \param clearingState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one when the call of this method ends).
 */
std::wstring MultiTapeMachineFactory::clearNumber(std::optional<std::wstring> clearingState, std::optional<std::wstring> endState) {
	if(!clearingState)
		clearingState = this->generator.getCurrentState();

	this->addSuperTransition<true, false, Machine::Direction::R>(clearingState, clearingState); // 1
	endState = this->addSuperTransition<false, false, Machine::Direction::R>(clearingState, endState); // 0

	return (*endState);
};

/*!
 * This method finds the end of the current tape.
 * It expects the machine to be at the beginning of a number on the tape (or anywhere on a valid position on the tape if the tape is empty).
 * \param findingEndState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one when the call of this method ends).
 * \param tape If non-zero, the method expects to start on this tape and the zeroth tape will be marked in case that this tape has something beyond the end of the zeroth tape.
 */
std::wstring MultiTapeMachineFactory::findEnd(std::optional<std::wstring> findingEndState, std::optional<std::wstring> endState, size_t tape) {
	if(!findingEndState)
		findingEndState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::N>(findingEndState, {}); // 1
	this->skipNumber({}, findingEndState, tape);
	endState = this->addTransition<false, false, Machine::Direction::N>(findingEndState, endState); // 0

	return (*endState);
};

/*!
 * Make a journey from anywhere on tape 0 after the hole to the end of tapeB.
 * Place the symbol (1 on 0 depending on the start state) on the tapeB where the last 1 of the tapeB was.
 * A new 1 (end mark) will be placed thereafter.
 * It ends on the zeroth tape after the newly placed symbol.
 * \param goingToTheEndWith1State From this state, a 1 will be written. If {}, then the second start state has to be provided and this one isn’t considered.
 * \param goingToTheEndWith0State From this state, a 0 will be written. If {}, then the the start state has to be provided and this one isn’t considered.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one when the call of this method ends).
 * \param tapeB The destination tape of the copying.
 */
std::wstring MultiTapeMachineFactory::placeSymbol(std::optional<std::wstring> goingToTheEndWith1State, std::optional<std::wstring> goingToTheEndWith0State, std::optional<std::wstring> endState, size_t tapeB) {
	bool isNewEndStateNecessary;
	size_t tapesCount, x;
	std::wstring findingEndWith1State, findingEndWith0State, placedSymbolState, detectingStartCopyMarkState;

	if(!goingToTheEndWith0State && !goingToTheEndWith1State)
		throw UnexpectedError(L"Entrypoint with either 1 or 0 must be provided.");

	tapesCount = (this->tapesCount + 1);

	isNewEndStateNecessary = (!endState);

	if(!endState) {
		this->generator.increment();
		endState = this->generator.getCurrentState();
	};
	this->generator.increment();
	placedSymbolState = this->generator.getCurrentState();

	if(goingToTheEndWith1State) {
		this->addSuperTransition<true, true, Machine::Direction::R>(goingToTheEndWith1State, goingToTheEndWith1State); // 1

		this->addTransition<false, false, Machine::Direction::L>(goingToTheEndWith1State, {}); // 0
		for(x = tapesCount - 1; x > tapeB; x--)
			this->addTransition<Machine::Direction::L>({}, {});
		findingEndWith1State = this->generator.getCurrentState();

		// The machine is now on the tapeB.
		// The end of this tape has to be found now.

		this->addSuperTransition<false, false, Machine::Direction::L>(findingEndWith1State, findingEndWith1State); // 0
		this->addSuperTransition<true, true, Machine::Direction::R>(findingEndWith1State, placedSymbolState); // 1; place 1
	};

	if(goingToTheEndWith0State) {
		this->addSuperTransition<true, true, Machine::Direction::R>(goingToTheEndWith0State, goingToTheEndWith0State); // 1

		this->addTransition<false, false, Machine::Direction::L>(goingToTheEndWith0State, {}); // 0
		for(x = tapesCount - 1; x > tapeB; x--)
			this->addTransition<Machine::Direction::L>({}, {});
		findingEndWith0State = this->generator.getCurrentState();

		// The machine is now on the tapeB.
		// The end of this tape has to be found now.

		this->addSuperTransition<false, false, Machine::Direction::L>(findingEndWith0State, findingEndWith0State); // 0
		this->addSuperTransition<true, false, Machine::Direction::R>(findingEndWith0State, placedSymbolState); // 1; place 0
	};

	this->addTransition<false, true, Machine::Direction::L>(placedSymbolState, {}); // Place new end
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	// The symbol is placed and the machine is on the tape 0.
	// If there is 0, a 1 should be written to preserve integrity.

	this->addTransition<true, true, Machine::Direction::N>({}, endState);
	detectingStartCopyMarkState = this->addSuperTransition<false, true, Machine::Direction::R>({}, {});

	// But what if the 0 on the tape 0 was the hole that marks the copying?
	// This can be determined by checking if there is a 1 after that 0 on tape 0.
	// If it is the case, the 1 must be changed back to 0.
	// There is an edge case where the 0 is at the end of the zeroth tape.
	// But not keeping it does not break the copying, as it would stop in the next step in either case.

	this->addSuperTransition<false, false, Machine::Direction::L>(detectingStartCopyMarkState, endState); // 0
	this->addSuperTransition<true, true, Machine::Direction::L>(detectingStartCopyMarkState, {}); // 1
	this->addSuperTransition<true, false, Machine::Direction::L>({}, endState);

	if(isNewEndStateNecessary)
		return this->addTransition<true, true, Machine::Direction::N>(endState, {});
	else
		return (*endState);
};

/*!
 * Return to the hole after placeSymbol().
 * \param returningToAState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one when the call of this method ends).
 * \param tapeA The source tape of the copying.
 * \param tapeB The destination tape of the copying.
 */
std::wstring MultiTapeMachineFactory::returnToMark(std::optional<std::wstring> returningToAState, std::optional<std::wstring> endState, size_t tapeA, size_t tapeB) {
	bool isNewEndStateNecessary = false;
	size_t tapesCount, x;
	std::wstring atTheBeginningState, atTheStartHoleState, returningToAState2;

	tapesCount = (this->tapesCount + 1);

	isNewEndStateNecessary = (!endState);

	if(!returningToAState)
		returningToAState = this->generator.getCurrentState();

	this->addSuperTransition<true, true, Machine::Direction::L>(returningToAState, returningToAState); // 1
	this->addSuperTransition<false, false, Machine::Direction::L>(returningToAState, {}); // 0
	atTheBeginningState = this->addTransition<false, false, Machine::Direction::N>({}, {}); // 00
	endState = this->addSuperTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), endState); // 10

	this->generator.increment();
	atTheStartHoleState = this->generator.getCurrentState();

	// The machine is now at the beginning of tapeB.
	// Now, it has to find the hole at tape 0.
	// The first case that can happen is that the hole is at the beginning.
	// If the last 0 before the first 1 on the tape 0 is accompanied by a 1 on tapeA, this is the case.

	this->addSuperTransition<false, false, Machine::Direction::R>(atTheBeginningState, {});
	for(x = 0; x < tapesCount; x++) {
		if(x==tapeA) {
			this->addTransition<true, true, Machine::Direction::N>({}, atTheStartHoleState); // The 0 on the tape 0 was a hole
			this->addTransition<false, false, Machine::Direction::R>({}, {});
		}
		else
			this->addTransition<Machine::Direction::R>({}, {});
	};

	returningToAState2 = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::L>(atTheStartHoleState, {});
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->addTransition<false, false, Machine::Direction::N>({}, endState); // This is exactly where the start hole is

	// The hole wasn’t at the beginning.
	// Let’s find it.

	this->addSuperTransition<true, true, Machine::Direction::R>(returningToAState2, returningToAState2); // 1
	this->addTransition<false, false, Machine::Direction::N>(returningToAState2, endState); // 0

	if(isNewEndStateNecessary)
		return this->addTransition<false, false, Machine::Direction::N>(endState, {});
	else
		return (*endState);
};

/*!
 * Copy a single number from tapeA from this position on to the end of tapeB.
 * It expects the machine to be on the zeroth tape.
 * It ends on the zeroth tape where the next symbol would be.
 * The number must be there.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tapeA The source tape.
 * \param tapeB The destination tape.
 */
std::wstring MultiTapeMachineFactory::copySingleNumber(std::optional<std::wstring> startState, std::optional<std::wstring> endState, size_t tapeA, size_t tapeB) {
	bool isNewEndStateNecessary;
	size_t tapesCount, x;
	std::wstring copyState, goingToTheEndWith1State;

	tapesCount = (this->tapesCount + 1);

	isNewEndStateNecessary = (!endState);

	if(!startState)
		startState = this->generator.getCurrentState();

	if(!endState) {
		this->generator.increment();
		endState = this->generator.getCurrentState();
	};

	goingToTheEndWith1State = this->addSuperTransition<true, false, Machine::Direction::R>(startState, {}); // Mark the copying with a hole on the zeroth tape
	this->placeSymbol(goingToTheEndWith1State, {}, {}, tapeB); // The placeSymbol() function can be called now, the machine is behind the hole
	this->returnToMark({}, {}, tapeA, tapeB);
	this->addSuperTransition<false, true, Machine::Direction::R>({}, {}); // Remove the hole

	// A single symbol was copied.
	// Now, it has to be decided whether the number continues.

	this->addTransition<false, false, Machine::Direction::N>({}, endState); // There is nothing more on the zeroth tape, so the number ends here for sure
	this->addTransition<true, false, Machine::Direction::R>({}, {}); // The zeroth tape does not end here, place a hole in case there is another 1 on tapeA
	for(x = 1; x < tapeA; x++)
		this->addTransition<Machine::Direction::R>({}, {});
	copyState = this->generator.getCurrentState();

	// If the machine looks at 1 now, it has to copy another symbol.
	// If not, the whole number is already copied.

	this->addTransition<true, true, Machine::Direction::R>(copyState, {}); // 1
	for(x = (tapeA + 1); x < tapesCount; x++)
		this->addTransition<Machine::Direction::R>({}, {});
	this->addTransition<Machine::Direction::N>({}, goingToTheEndWith1State);

	this->addTransition<false, false, Machine::Direction::L>(copyState, {}); // 0
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->addTransition<false, true, Machine::Direction::N>({}, endState); // Remove the new hole

	if(isNewEndStateNecessary)
		return this->addTransition<Machine::Direction::N>(endState, {});
	else
		return (*endState);
};

/*!
 * Copy a single number followed by a single 0 from tapeA from this position on to the end of tapeB.
 * It expects the machine to be on the zeroth tape.
 * It ends on the zeroth tape where the next symbol would be.
 * The number must be there.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tapeA The source tape.
 * \param tapeB The destination tape.
 */
std::wstring MultiTapeMachineFactory::copySingleNumberAndZero(std::optional<std::wstring> startState, std::optional<std::wstring> endState, size_t tapeA, size_t tapeB) {
	if(!startState)
		startState = this->generator.getCurrentState();

	// copySingleNumber() does the copying of the number.
	// Then, placeSymbol() will copy the single 0.

	this->copySingleNumber(startState, {}, tapeA, tapeB);
	this->addSuperTransition<true, false, Machine::Direction::R>({}, {}); // Mark this position with a hole on the zeroth tape
	this->placeSymbol({}, this->generator.getCurrentState(), {}, tapeB); // Provide the current state as the goingToTheEndWith0State
	this->returnToMark({}, {}, tapeA, tapeB);
	endState = this->addSuperTransition<false, true, Machine::Direction::R>({}, endState); // Remove the hole.

	return (*endState);
};

/*!
 * Copy everything from tapeA from this position on to the end of tapeB.
 * It expects the machine to be on the zeroth tape.
 * At least one number must be there to be copied.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tapeA The source tape.
 * \param tapeB The destination tape.
 */
std::wstring MultiTapeMachineFactory::copyFromHere(std::optional<std::wstring> startState, std::optional<std::wstring> endState, size_t tapeA, size_t tapeB) {
	size_t tapesCount, x;
	std::wstring copyState, goingToTheEndWith1State, findingEndWith1State, finishedCopyState, finishedCopyState2, goingToTheEndWith0State, findingEndWith0State, clearingEndState;

	tapesCount = (this->tapesCount + 1);

	if(!startState)
		startState = this->generator.getCurrentState();

	// Each iteration of copying is performed by placeSymbol() and returnToMark().
	// A hole on the zeroth tape (a 0) indicates where the next symbol which is to be copied is.
	// The first iteration can start right away (and it is going to be a one).

	goingToTheEndWith1State = this->addSuperTransition<true, false, Machine::Direction::R>(startState, {}); // Mark this position as a hole on the zeroth tape
	this->generator.increment();
	goingToTheEndWith0State = this->generator.getCurrentState();

	this->placeSymbol(goingToTheEndWith1State, goingToTheEndWith0State, {}, tapeB);
	this->returnToMark({}, {}, tapeA, tapeB);

	// Now, an iteration has just ended. The hole has to be moved.

	this->addSuperTransition<false, true, Machine::Direction::R>({}, {}); // Fill the current hole
	finishedCopyState = this->addTransition<false, false, Machine::Direction::N>({}, {}); // This was the end of the zeroth tape, no chance of something more being on tapeA
	this->addTransition<true, false, Machine::Direction::R>(this->generator.getLastState(), {}); // There is a one on the zeroth tape, but that doesn’t mean that there is something on tapeA; create a new hole
	for(x = 1; x < tapeA; x++)
		this->addTransition<Machine::Direction::R>({}, {});
	copyState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::R>(copyState, {}); // 1; there is definitely something more to copy
	for(x = (tapeA + 1); x < tapesCount; x++)
		this->addTransition<Machine::Direction::R>({}, {});
	this->addTransition<Machine::Direction::N>({}, goingToTheEndWith1State);

	this->addSuperTransition<false, false, Machine::Direction::R>(copyState, {}); // 0; let’s check if this is just a delimiter, or if it’s really the end
	finishedCopyState2 = this->addTransition<false, false, Machine::Direction::L>({}, {}); // 00; this is the end of tapeA
	this->addTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), {}); // 01; it was not the end, let’s copy the 0
	for(x = (tapeA + 1); x < tapesCount; x++)
		this->addTransition<Machine::Direction::R>({}, {});
	this->addTransition<Machine::Direction::N>({}, goingToTheEndWith0State);

	// Only the ending has to be sorted out.
	// If the machine is in findingEndState2, the new hole has to be removed.

	this->addTransition<Machine::Direction::L>(finishedCopyState2, {});
	for(x = (tapesCount + tapeA - 2); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->addTransition<false, true, Machine::Direction::N>({}, finishedCopyState); // Fill the hole

	// Let’s remove the last 1 of tapeB.
	// The machine will go to the end of the zeroth tape and then find the end of tapeB.

	this->addSuperTransition<true, true, Machine::Direction::R>(finishedCopyState, finishedCopyState); // 1
	this->addTransition<false, false, Machine::Direction::L>(finishedCopyState, {}); // 0
	for(x = (tapesCount - 1); x > tapeB; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	clearingEndState = this->generator.getCurrentState();

	this->addSuperTransition<false, false, Machine::Direction::L>(clearingEndState, clearingEndState); // 0
	this->addTransition<true, false, Machine::Direction::L>(clearingEndState, {}); // 1; clear end
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	endState = this->goHome({}, endState);

	return (*endState);
};

/*!
 * Copy some number of numbers from tapeA from this position on to the end of tapeB.
 * tapeB is expected to end with the number 0 (so a single one), this will be rewritten.
 * It expects the machine to be on the zeroth tape.
 * At least one number must be there to be copied.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tapeA The source tape.
 * \param tapeB The destination tape.
 * \param count The number of numbers.
 */
std::wstring MultiTapeMachineFactory::copyFromHere(std::optional<std::wstring> startState, std::optional<std::wstring> endState, size_t tapeA, size_t tapeB, size_t count) {
	size_t tapesCount, x;
	std::wstring finishedCopyState, clearingEndState;

	tapesCount = (this->tapesCount + 1);

	if(!startState)
		startState = this->generator.getCurrentState();

	for(x = 0; x < count - 1; x++)
		this->copySingleNumberAndZero((x==0) ? startState : std::nullopt, {}, tapeA, tapeB);
	this->copySingleNumber((x==0) ? startState : std::nullopt, {}, tapeA, tapeB);
	finishedCopyState = this->generator.getCurrentState();

	// The copying is done.
	// Let’s clear the last 1 of tapeB.
	// The machine goes first to the end of the zeroth tape and then finds the end of tapeB.

	this->addSuperTransition<true, true, Machine::Direction::R>(finishedCopyState, finishedCopyState); // 1
	this->addTransition<false, false, Machine::Direction::L>(finishedCopyState, {}); // 0
	for(x = (tapesCount - 1); x > tapeB; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	clearingEndState = this->generator.getCurrentState();

	this->addSuperTransition<false, false, Machine::Direction::L>(clearingEndState, clearingEndState); // 0
	this->addTransition<true, false, Machine::Direction::L>(clearingEndState, {}); // 1; clear end
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	endState = this->goHome({}, endState);

	return (*endState);
};

/*!
 * Copy everything from tapeA[beginA:] to the end of tapeB.
 * tapeB is expected to end with the number 0 (so a single one), this will be rewritten.
 * The copying is canceled if there is nothing after beginA.
 * \param readyState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 * \param tapeA The source tape.
 * \param tapeB The destination tape.
 * \param beginA From where on to copy.
 */
std::wstring MultiTapeMachineFactory::copyIfNonEmpty(std::optional<std::wstring> readyState, std::optional<std::wstring> endState, size_t tapeA, size_t tapeB, size_t beginA) {
	size_t x;
	std::wstring returningToMarkedAreaState, skippedCopyingState;

	if(!readyState)
		readyState = this->generator.getCurrentState();

	this->findTape(tapeA, readyState, {});

	for(x = 0; x < beginA; x++)
		this->skipNumber({}, {});

	readyState = this->generator.getCurrentState();

	// The machine is now at beginA.
	// Let’s suppose that tapeA ends here.

	this->addTransition<false, false, Machine::Direction::L>(readyState, {}); // 0; Nothing to copy
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	returningToMarkedAreaState = this->generator.getCurrentState();

	// Now, the machine goes home, but goHome() does not expect the machine to be behind the area marked by the zeroth tape.

	this->addSuperTransition<false, false, Machine::Direction::L>(returningToMarkedAreaState, returningToMarkedAreaState); // 0
	this->addTransition<true, true, Machine::Direction::N>(returningToMarkedAreaState, {}); // 1
	this->goHome({}, {});

	this->findTape(tapeB, {}, {}, false);
	this->findEnd({}, {});

	this->addSuperTransition<false, false, Machine::Direction::L>({}, {});
	this->addSuperTransition<false, false, Machine::Direction::L>({}, {});

	this->addTransition<true, false, Machine::Direction::L>({}, {}); // Remove the single one marking the copying.
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	skippedCopyingState = this->goHome({}, {});

	// Now, what if there is something to copy?
	// The copying is performed by copyFromHere(), which requires the machine to be at the zeroth tape on the beginA position.

	this->addTransition<true, true, Machine::Direction::L>(readyState, {}); // 1; Something to copy
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	endState = this->copyFromHere({}, endState, tapeA, tapeB);

	this->addTransition<true, true, Machine::Direction::N>(skippedCopyingState, *endState);

	return (*endState);
};

/*!
 * Add an extra number 0 (a single symbol one) to the beginning of a tape.
 * \tape The tape.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 */
std::wstring MultiTapeMachineFactory::addDummyZero(size_t tape, std::optional<std::wstring> startState, std::optional<std::wstring> endState) {
	size_t tapesCount, x;

	tapesCount = (this->tapesCount + 1);

	this->findTape(tape, startState, {}, false);
	for(x = 0; x < 2 * tapesCount; x++) {
		if(x==tape + tapesCount) {
			this->addTransition<false, true, Machine::Direction::L>({}, {}); // Make sure that the zeroth tape is marked
			this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), this->generator.getCurrentState());
		}
		else
			this->addTransition<Machine::Direction::L>({}, {});
	};
	this->addTransition<false, true, Machine::Direction::L>({}, {}); // Insert the dummy 0
	for(x = (tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->addTransition<false, true, Machine::Direction::N>({}, {}); // Make sure that the zeroth tape is marked
	this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), this->generator.getCurrentState());
	endState = this->goHome({}, endState);

	return (*endState);
};

/*!
 * Remove the added extra number 0 (a single symbol one) from the beginning of a tape.
 * \tape The tape.
 * \param startState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 */
std::wstring MultiTapeMachineFactory::removeDummyZero(size_t tape, std::optional<std::wstring> startState, std::optional<std::wstring> endState) {
	size_t x;

	this->findTape(tape, startState, {});
	this->addTransition<true, false, Machine::Direction::L>({}, {});
	for(x = (tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	endState = this->goHome({}, endState);

	return (*endState);
};


/*!
 * This method initializes the multi-tape system, writing the original data to the input tape.
 * \param inputTape The number of the input tape (0 < inputTape ≤ tapesCount).
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::decompress(size_t inputTape) {
	size_t tapesCount, x;
	std::wstring startState, findingEndState, returningHomeState, carryOneState, carryZeroState, carryOneState2, carryZeroState2, goingHomeState, goingHomeState2, endState;

	if(inputTape==0 || inputTape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	startState = this->generator.getCurrentState();

	// Each symbol is going to be copied from the beginning of the original tape to the newly forming input tape.
	// The leftmost 1 on the tape is always going to be where the last copied symbol was.
	carryOneState = this->addTransition<true, true, Machine::Direction::R>(startState, {}); // 1
	this->addTransition<false, true, Machine::Direction::R>(startState, {}); // 0
	carryZeroState = this->addTransition<true, true, Machine::Direction::R>({}, {}); // 01
	endState = this->addTransition<false, false, Machine::Direction::L>(this->generator.getLastState(), {}); // 00

	// When in carryOneState or carryZeroState, the machine has to go through the rest of the original tape.
	// When 00 is found, the original tape ends.

	// 1←x → 1x←
	this->addTransition<true, true, Machine::Direction::R>(carryOneState, carryOneState); // 1 (carry 1)
	this->addTransition<true, true, Machine::Direction::R>(carryZeroState, carryZeroState); // 1 (carry 0)

	// 0←1x → 01x←
	// 0←0x → 00x←
	this->addTransition<false, false, Machine::Direction::R>(carryOneState, {}); // 0 (carry 1)
	this->addTransition<true, true, Machine::Direction::R>({}, carryOneState); // 01 (carry 1)
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00 (carry 1)

	// The machine is now 3 cells right of the rightmost 1 of the original tape.
	// There needs to be a large enough gap, so that the beginning of the zeroth tape is clear.
	for(x = 3; x <= tapesCount; x++)
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	carryOneState2 = this->generator.getCurrentState();

	this->addTransition<false, false, Machine::Direction::R>(carryZeroState, {}); // 0 (carry 0)
	this->addTransition<true, true, Machine::Direction::R>({}, carryZeroState); // 01 (carry 0)
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00 (carry 0)

	// The machine is now 3 cells right of the rightmost 1 of the original tape.
	// There needs to be a large enough gap, so that the beginning of the zeroth tape is clear.
	for(x = 3; x <= tapesCount; x++)
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	carryZeroState2 = this->generator.getCurrentState();

	// When in carryOneState2 or carryZeroState2, the machine has to go until the end is found.

	this->addSuperTransition<true, true, Machine::Direction::R>(carryOneState2, carryOneState2); // 1 (carry 1)
	this->addTransition<false, true, Machine::Direction::R>(carryOneState2, {}); // 0 (carry 1)
	for(x = 1; x < inputTape; x++)
			this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<false, true, Machine::Direction::L>({}, {}); // Place 1
	// Return to the zeroth tape.
	for(x = (inputTape - 1); x > 0; x--)
		this->addTransition<false, false, Machine::Direction::L>({}, {});
	goingHomeState = this->generator.getCurrentState();

	this->addSuperTransition<true, true, Machine::Direction::R>(carryZeroState2, carryZeroState2); // 1 (carry 0)
	this->addTransition<false, true, Machine::Direction::N>(carryZeroState2, goingHomeState); // 0 (carry 0)
	// No need to place 0, it is already there.

	// The symbol is copied, so the machine has to return to the beginning for the next one.

	this->addSuperTransition<true, true, Machine::Direction::L>(goingHomeState, goingHomeState); // 1
	goingHomeState2 = this->addTransition<false, false, Machine::Direction::L>(goingHomeState, {}); // 0

	this->addTransition<true, true, Machine::Direction::L>(goingHomeState2, goingHomeState2); // 1
	this->addTransition<false, false, Machine::Direction::L>(goingHomeState2, {}); // 0
	this->addTransition<true, true, Machine::Direction::L>({}, goingHomeState2); // 10
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00
	this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<true, false, Machine::Direction::R>({}, startState);

	// The original tape is all consumed, so the machine has to delete the last 1 and move to the beginning of the zeroth tape.
	this->addTransition<true, false, Machine::Direction::R>(endState, {});
	for(x = 1; x < tapesCount; x++)
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<false, true, Machine::Direction::N>({}, {}); // For empty tape
	this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), this->generator.getCurrentState());

	return (*this);
};

/*!
 * This method destroys the multi-tape system, leaving only the contents of the output tape.
 * \param outputTape The number of the output tape (0 < outputTape ≤ tapesCount).
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::compress(size_t outputTape) {
	size_t tapesCount, x;
	std::wstring startState, beginningState, deletingState, findingEndState, startCopyState, carryOneState, carryOneState2, returningState, returningState2, copyState, carryZeroState, carryZeroState2, endingState, findingEndState2;

	if(outputTape==0 || outputTape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	// The first thing that the machine does is the finding of the beginning of the output tape.
	// Everything before the beginning is zeroed out.

	startState = this->generator.getCurrentState();
	this->generator.increment();
	beginningState = this->generator.getCurrentState();

	this->addTransition<true, false, Machine::Direction::R>(startState, {});
	for(x = 1; x < tapesCount - 1; x++) {
		if(x==outputTape) {
			this->addTransition<false, false, Machine::Direction::R>({}, {});
			this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), beginningState);
		}
		else {
			this->addTransition<true, false, Machine::Direction::R>({}, {});
			this->addTransition<false, false, Machine::Direction::R>(this->generator.getLastState(), this->generator.getCurrentState());
		};
	};
	if(x==outputTape) {
		this->addTransition<false, false, Machine::Direction::R>({}, startState);
		this->addTransition<true, true, Machine::Direction::L>({}, beginningState);
	}
	else {
		this->addTransition<true, false, Machine::Direction::R>({}, startState);
		this->addTransition<false, false, Machine::Direction::R>({}, startState);
	};

	// A mark gets placed to the left of the beginning.

	this->addTransition<false, false, Machine::Direction::L>(beginningState, {});
	for(x = 2; x < 3 * tapesCount; x++)
		this->addTransition<false, false, Machine::Direction::L>({}, {});
	this->addTransition<false, true, Machine::Direction::R>({}, {}); // Place end mark, here shall the copied tape begin
	for(x = 1; x < 3 * tapesCount - outputTape; x++)
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	deletingState = this->addTransition<false, true, Machine::Direction::N>({}, {});

	// Now everything except for the output tape gets deleted.

	this->addTransition<true, false, Machine::Direction::R>(deletingState, {}); // 1 (on the zeroth tape)
	for(x = 1; x < tapesCount - 1; x++) {
		if(x==outputTape)
			this->addTransition<Machine::Direction::R>({}, {});
		else {
			this->addTransition<true, false, Machine::Direction::R>({}, {});
			this->addTransition<false, false, Machine::Direction::R>(this->generator.getLastState(), this->generator.getCurrentState());
		};
	};
	if(x==outputTape)
		this->addTransition<Machine::Direction::R>({}, deletingState);
	else {
		this->addTransition<true, false, Machine::Direction::R>({}, deletingState);
		this->addTransition<false, false, Machine::Direction::R>({}, deletingState);
	};

	this->addTransition<false, false, Machine::Direction::L>(deletingState, {}); // 0 (on the zeroth tape)

	// The machine is now at the end of the written part of the tape.
	// Now it needs to find where the end of the output tape is.

	for(x = tapesCount - 1; x > outputTape; x--)
		this->addTransition<false, false, Machine::Direction::L>({}, {});
	findingEndState = this->generator.getCurrentState();

	this->addSuperTransition<false, false, Machine::Direction::L>(findingEndState, findingEndState);
	carryOneState = this->addSuperTransition<true, true, Machine::Direction::L>(findingEndState, {});

	// The last symbol on the output tape has to be 1, the machine now carries it to the beginning.
	// The 1 remains there, it serves now as the end marker.

	this->addSuperTransition<true, true, Machine::Direction::L>(carryOneState, carryOneState); // 1
	this->addSuperTransition<false, false, Machine::Direction::L>(carryOneState, {}); // 0
	this->addTransition<true, true, Machine::Direction::N>({}, carryOneState); // 10
	this->addTransition<false, false, Machine::Direction::L>({}, {}); // 00
	this->addTransition<false, false, Machine::Direction::L>({});

	// The machine now searches for the copied part of the output tape.
	// If this is the first iteration, only the single 1 is there.

	carryOneState2 = this->addTransition<true, true, Machine::Direction::L>({}, {});

	// The symbol has to be carried all the way to the left end.

	this->addTransition<true, true, Machine::Direction::L>(carryOneState2); // 1
	this->addTransition<false, false, Machine::Direction::L>(carryOneState2, {}); // 0
	this->addTransition<true, true, Machine::Direction::L>({}, carryOneState2); // 10
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00

	// The machine now turns around, moving the end mark further left.
	// The old end mark serves now as the new 1 symbol.

	returningState = this->addTransition<false, true, Machine::Direction::R>({}, {}); // Place new end mark
	this->addTransition<true, true, Machine::Direction::R>(returningState, returningState); // 1
	this->addTransition<false, false, Machine::Direction::R>(returningState, {}); // 0
	this->addTransition<true, true, Machine::Direction::R>({}, returningState); // 01
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00
	this->addTransition<false, false, Machine::Direction::R>({});
	returningState2 = this->addSuperTransition<true, true, Machine::Direction::R>({}, {});

	// Let the machine find the end again.

	this->addSuperTransition<true, true, Machine::Direction::R>(returningState2, returningState2); // 1
	this->addSuperTransition<false, false, Machine::Direction::R>(returningState2, {}); // 0
	this->addTransition<true, true, Machine::Direction::N>({}, returningState2); // 01
	this->addTransition<false, false, Machine::Direction::L>({}, {}); // 00
	this->addTransition<false, false, Machine::Direction::L>({});
	copyState = this->addSuperTransition<true, false, Machine::Direction::L>({}, {}); // Remove end mark

	// Now the machine looks at the symbol which should be carried to the beginning.

	this->addSuperTransition<true, true, Machine::Direction::L>(copyState, carryOneState); // 1, leave it there as the end mark
	this->addSuperTransition<false, true, Machine::Direction::L>(copyState, {}); // 0, change it to 1 as the end mark
	endingState = this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00
	carryZeroState = this->addSuperTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {}); // 10

	// Carrying 0 is like carrying 1.

	this->addSuperTransition<true, true, Machine::Direction::L>(carryZeroState, carryZeroState); // 1
	this->addSuperTransition<false, false, Machine::Direction::L>(carryZeroState, {}); // 0
	this->addTransition<true, true, Machine::Direction::N>({}, carryZeroState); // 10
	this->addTransition<false, false, Machine::Direction::L>({}, {}); // 00
	this->addTransition<false, false, Machine::Direction::L>({});
	carryZeroState2 = this->addTransition<true, true, Machine::Direction::L>({}, {});

	this->addTransition<true, true, Machine::Direction::L>(carryZeroState2); // 1
	this->addTransition<false, false, Machine::Direction::L>(carryZeroState2, {}); // 0
	this->addTransition<true, true, Machine::Direction::L>({}, carryZeroState2); // 10
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00
	this->addTransition<false, true, Machine::Direction::R>({}, {}); // Place new end mark
	this->addTransition<true, false, Machine::Direction::R>({}, returningState); // Place 0 (where the old end mark was)

	// This is the time when everything is moved from the output tape to the beginning.

	this->addTransition<false, false, Machine::Direction::R>(endingState, {});
	for(x = 2; x < tapesCount; x++)
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<true, false, Machine::Direction::L>({}, {}); // The machine placed a new end mark here, not knowing that all is already moved
	this->addTransition<false, false, Machine::Direction::L>({});
	findingEndState2 = this->addTransition<true, true, Machine::Direction::L>({}, {});

	this->addTransition<true, true, Machine::Direction::L>(findingEndState2); // 1
	this->addTransition<false, false, Machine::Direction::L>(findingEndState2, {}); // 0
	this->addTransition<true, true, Machine::Direction::L>({}, findingEndState2); // 10
	this->addTransition<false, false, Machine::Direction::R>({}, {}); // 00
	this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<true, false, Machine::Direction::R>({}, {}); // Remove the end mark, stop on the symbol to the right, which is the first symbol of the tape

	this->addTransition<false, false, Machine::Direction::N>(startState, this->generator.getCurrentState()); // Empty output, passed the end of the zeroth band

	return (*this);
};

/*!
 * This method clears numbers from the beginning of a tape.
 * The behavior is undefined if there is not enough numbers on the tape (less than count).
 * \param tape The number of the tape (0 < tape ≤ tapesCount).
 * \param count How many numbers to clear.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::clearBeginning(size_t tape, size_t count) {
	size_t tapesCount, x;
	Machine machine;

	if(tape==0 || tape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(count==0)
		throw UnexpectedError(L"Invalid count.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	this->findTape(tape, {}, {}, false);

	for(x = 0; x < count; x++)
		this->clearNumber({}, {});

	for(x = (2 * tapesCount + tape); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	this->goHome({}, {});

	return (*this);;
};

/*!
 * This method clears numbers from the end of a tape.
 * The behavior is undefined if there is not enough numbers on the tape (less than begin).
 * \param tape The number of the tape (0 < tape ≤ tapesCount).
 * \param begin From where to clear (how many numbers to keep).
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::clearEnd(size_t tape, size_t begin) {
	size_t tapesCount, x;
	std::wstring emptyTapeState, clearingState, endState;
	Machine machine;

	if(tape==0 || tape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	this->findTape(tape, {}, {});
	if(begin==0) {
		emptyTapeState = this->addTransition<false, false, Machine::Direction::N>({}, {});
		this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), {});
	};
	for(x = 0; x < begin; x++)
		this->skipNumber({}, {});
	clearingState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::N>(clearingState, {});
	this->clearNumber({}, clearingState);

	this->addTransition<false, false, Machine::Direction::L>(clearingState, {});
	for(x = (2 * tapesCount + tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	endState = this->goHome({}, {});

	if(begin==0) {
		this->addTransition<false, false, Machine::Direction::L>(emptyTapeState, {});
		for(x = (tape - 1); x > 0; x--)
			this->addTransition<Machine::Direction::L>({}, {});

		this->addTransition<true, true, Machine::Direction::N>(endState, generator.getCurrentState());
	};

	return (*this);
};

/*!
 * This method writes a number (n + 1 ones after one zero) somewhere on a tape.
 * If there is something more on the tape behind the target position, it gets deleted.
 * The behavior is undefined if there is not enough numbers on the tape (less than begin).
 * \param tape The number of the tape.
 * \param begin The target position (0 is the beginning).
 * \param number The number to be written.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::writeNumber(size_t tape, size_t begin, size_t number) {
	size_t tapesCount, x;
	std::wstring clearingState;

	if(tape==0 || tape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	this->findTape(tape, {}, {});
	for(x = 0; x < begin; x++)
		this->skipNumber({}, {}, tape);

	// The machine is now at the target position.

	for(x = 0; x <= number; x++) {
		this->addTransition<true, true, Machine::Direction::N>({}, {});
		this->addTransition<false, true, Machine::Direction::N>(this->generator.getLastState(), this->generator.getCurrentState());
		this->addSuperTransition<true, true, Machine::Direction::R>({}, {}, (x==number) ? 0 : tape);
	};
	clearingState = this->generator.getCurrentState();

	// The number is written down.
	// What remains on the tape from here on has to be taken care of.

	this->addSuperTransition<true, false, Machine::Direction::R>(clearingState, clearingState); // 1
	this->addSuperTransition<false, false, Machine::Direction::R>(clearingState, {}); // 0
	this->addTransition<true, true, Machine::Direction::N>({}, clearingState); // 01
	this->addTransition<false, false, Machine::Direction::L>({}, {}); // 00
	for(x = (2 * tapesCount + tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	return (*this);
};

/*!
 * This method writes a number (n + 1 ones after one zero) behind the last number.
 * If the tape is empty, it writes it on a valid position.
 * \param tape The number of the tape.
 * \param number The number to be written.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::appendNumber(size_t tape, size_t number) {
	size_t x;

	if(tape==0 || tape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	this->findTape(tape, {}, {});
	this->findEnd({}, {}, tape);

	for(x = 0; x < number; x++)
		this->addSuperTransition<false, true, Machine::Direction::R>({}, {}, tape);
	this->addTransition<false, true, Machine::Direction::L>({}, {});

	for(x = (tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	return (*this);
};

/*!
 * Copy all numbers from tapeA[beginA:] to tapeB[beginB:].
 * Everything in tapeB[beginB:] is deleted.
 * The behavior is undefined if beginA is less than the length of tapeA or if beginB is less than the length of tapeB.
 * The source and destination tape must not be the same.
 * \param tapeA The source tape.
 * \param beginA From which number on to copy.
 * \param tapeB The destination tape.
 * \param beginB The destination (how far from the beginning).
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::copyAll(size_t tapeA, size_t beginA, size_t tapeB, size_t beginB) {
	size_t x;
	std::wstring clearingState, skippedClearingState, returningToMarkedAreaState;

	if(tapeA==0 || tapeA > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeA.");

	if(tapeB==0 || tapeB > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeB.");

	if(tapeA==tapeB)
		throw UnexpectedError(L"tapeA and tapeB must not be the same tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	// The first thing to do is to clear everything behind beginB.

	this->findTape(tapeB, {}, {});
	for(x = 0; x < beginB; x++)
		this->skipNumber({}, {});
	skippedClearingState = this->addTransition<false, false, Machine::Direction::N>({}, {}); // If there is nothing behind beginB
	this->addSuperTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), {}); // Keep this 1 here, because copyIfNonEmpty() requires it
	clearingState = this->addTransition<false, true, Machine::Direction::N>({}, {}); // Write a 1 to guarantee that clearNumber can start straight away
	this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), clearingState);

	this->addTransition<true, true, Machine::Direction::N>(clearingState, {}); // 1
	this->clearNumber({}, clearingState);

	this->addTransition<false, false, Machine::Direction::L>(clearingState, {}); // 0
	this->addTransition<false, true, Machine::Direction::L>(skippedClearingState, this->generator.getCurrentState());

	// The clearing is now over.
	// Now, the machine goes home, but goHome() does not expect the machine to be behind the area marked by the zeroth tape.

	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	returningToMarkedAreaState = this->generator.getCurrentState();

	this->addSuperTransition<false, true, Machine::Direction::L>(returningToMarkedAreaState, returningToMarkedAreaState); // 0
	this->addTransition<true, true, Machine::Direction::N>(returningToMarkedAreaState, {}); // 1
	this->goHome({}, {});

	// The copying itself is delegated to copyIfNonEmpty().

	this->copyIfNonEmpty({}, {}, tapeA, tapeB, beginA);

	return (*this);
};

/*!
 * Copy all numbers from tapeA[beginA:] to the end of tapeB.
 * The behavior is undefined if beginA is less than the length of tapeA.
 * The source and destination tape must not be the same.
 * \param tapeA The source tape.
 * \param beginA From which number on to copy.
 * \param tapeB The destination tape.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::appendAll(size_t tapeA, size_t beginA, size_t tapeB) {
	size_t x;
	std::wstring clearingState, returningToMarkedAreaState;

	if(tapeA==0 || tapeA > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeA.");

	if(tapeB==0 || tapeB > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeB.");

	if(tapeA==tapeB)
		throw UnexpectedError(L"tapeA and tapeB must not be the same tape.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	// The copyIfNonEmpty() function requires a number 0 (a single one) at the destination at the end of endB.

	this->findTape(tapeB, {}, {});
	this->findEnd({}, {});

	this->addTransition<false, true, Machine::Direction::L>({}, {}); // Mark the destination for copyIfNonEmpty().
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	returningToMarkedAreaState = this->generator.getCurrentState();

	// Now, the machine goes home, but goHome() does not expect the machine to be behind the area marked by the zeroth tape.

	this->addSuperTransition<false, true, Machine::Direction::L>(returningToMarkedAreaState, returningToMarkedAreaState); // 0
	this->addTransition<true, true, Machine::Direction::N>(returningToMarkedAreaState, {}); // 1
	this->goHome({}, {});

	// The copying itself is delegated to copyIfNonEmpty().

	this->copyIfNonEmpty({}, {}, tapeA, tapeB, beginA);

	return (*this);
};

/*!
 * Copy some number of numbers starting from tapeA[beginA] to tapeB[beginB:].
 * Everything in tapeB[beginB:] is deleted.
 * The behavior is undefined if beginA + count is less than the length of tapeA or if beginB is less than the length of tapeB.
 * The source and destination tape must not be the same.
 * \param tapeA The source tape.
 * \param beginA From which number on to copy.
 * \param tapeB The destination tape.
 * \param beginB The destination (how far from the beginning).
 * \param count How many numbers to copy.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::copy(size_t tapeA, size_t beginA, size_t tapeB, size_t beginB, size_t count) {
	size_t x;
	std::wstring clearingState, skippedClearingState, returningToMarkedAreaState;

	if(tapeA==0 || tapeA > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeA.");

	if(tapeB==0 || tapeB > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeB.");

	if(tapeA==tapeB)
		throw UnexpectedError(L"tapeA and tapeB must not be the same tape.");

	if(count==0)
		throw UnexpectedError(L"count must not be 0.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	// The first thing to do is to clear everything behind beginB.

	this->findTape(tapeB, {}, {});
	for(x = 0; x < beginB; x++)
		this->skipNumber({}, {});
	skippedClearingState = this->addTransition<false, false, Machine::Direction::N>({}, {});
	this->addSuperTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), {});
	clearingState = this->addTransition<false, true, Machine::Direction::N>({}, {});
	this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), clearingState);

	this->addTransition<true, true, Machine::Direction::N>(clearingState, {});
	this->clearNumber({}, clearingState);

	this->addTransition<false, false, Machine::Direction::L>(clearingState, {});
	this->addTransition<false, true, Machine::Direction::L>(skippedClearingState, this->generator.getCurrentState());

	// The clearing is now over.
	// Now, the machine goes home, but goHome() does not expect the machine to be behind the area marked by the zeroth tape.

	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	returningToMarkedAreaState = this->generator.getCurrentState();

	this->addSuperTransition<false, true, Machine::Direction::L>(returningToMarkedAreaState, returningToMarkedAreaState); // 0
	this->addTransition<true, true, Machine::Direction::N>(returningToMarkedAreaState, {}); // 1
	this->goHome({}, {});

	// Find the source position tapeA[beginA].

	this->findTape(tapeA, {}, {});

	for(x = 0; x < beginA; x++)
		this->skipNumber({}, {});

	this->addTransition<true, true, Machine::Direction::L>({}, {});
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	// The copying itself is delegated to copyFromHere().

	this->copyFromHere({}, {}, tapeA, tapeB, count);

	return (*this);
};

/*!
 * Copy some number of numbers starting from tapeA[beginA] to the end of tapeB.
 * The behavior is undefined if beginA + count is less than the length of tapeA.
 * The source and destination tape must not be the same.
 * \param tapeA The source tape.
 * \param beginA From which number on to copy.
 * \param tapeB The destination tape.
 * \param count How many numbers to copy.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::append(size_t tapeA, size_t beginA, size_t tapeB, size_t count) {
	size_t x;
	std::wstring clearingState, returningToMarkedAreaState;

	if(tapeA==0 || tapeA > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeA.");

	if(tapeB==0 || tapeB > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeB.");

	if(tapeA==tapeB)
		throw UnexpectedError(L"tapeA and tapeB must not be the same tape.");

	if(count==0)
		throw UnexpectedError(L"count must not be 0.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	// The copyIfNonEmpty() function requires a number 0 (a single one) at the destination at the end of endB.

	this->findTape(tapeB, {}, {});
	this->findEnd({}, {});

	this->addTransition<false, true, Machine::Direction::L>({}, {}); // Mark the destination for copyIfNonEmpty().
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	returningToMarkedAreaState = this->generator.getCurrentState();

	// Now, the machine goes home, but goHome() does not expect the machine to be behind the area marked by the zeroth tape.

	this->addSuperTransition<false, true, Machine::Direction::L>(returningToMarkedAreaState, returningToMarkedAreaState); // 0
	this->addTransition<true, true, Machine::Direction::N>(returningToMarkedAreaState, {}); // 1
	this->goHome({}, {});


	// Find the source position tapeA[beginA].

	this->findTape(tapeA, {}, {});

	for(x = 0; x < beginA; x++)
		this->skipNumber({}, {});

	this->addTransition<true, true, Machine::Direction::L>({}, {});
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	// The copying itself is delegated to copyFromHere().

	this->copyFromHere({}, {}, tapeA, tapeB, count);

	return (*this);
};

/*!
 * This method accepts a Turing machine which will be simulated on a particular tape.
 * The simulated machine is expected to end with a valid state of the tape.
 * \param tape The tape on which the Turing machine will be simulated.
 * \param machine The Turing machine.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::simulate(size_t tape, const Machine &machine) {
	size_t tapesCount, x;
	std::vector<std::pair<std::wstring, bool>> missingTransitions;
	std::set<std::wstring> unusedStates;
	std::map<std::wstring, std::wstring> newStatesByOldStates;

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	this->findTape(tape, {}, {});
	machine.forEachTransition(
		[this, tape, tapesCount, &unusedStates, &missingTransitions, &newStatesByOldStates](const std::wstring &state, bool symbol, bool newSymbol, Machine::Direction direction, const std::wstring &newState) -> void {
			size_t x;

			if(!newStatesByOldStates.contains(state)) { // First time seing the incoming state
				newStatesByOldStates.emplace(state, this->generator.getCurrentState());
				this->generator.increment();
			}
			else
				unusedStates.erase(newStatesByOldStates.at(state));

			if(!newStatesByOldStates.contains(newState)) { // First time seing the outgoing state
				newStatesByOldStates.emplace(newState, this->generator.getCurrentState());
				unusedStates.insert(this->generator.getCurrentState()); // Not used as an incoming state yet, it might be deleted from this set in the future
				this->generator.increment();
			};

			// N-transitions are easy, but L-transitions and R-transitions require moving left/right to the next cell of this tape while ensuring that the zeroth tape is marked.

			if(direction==Machine::Direction::N)
				this->machine.addTransition(newStatesByOldStates.at(state), symbol, newSymbol, direction, newStatesByOldStates.at(newState));
			else {
				this->machine.addTransition(newStatesByOldStates.at(state), symbol, newSymbol, direction, this->generator.getCurrentState());
				for(x = 1; x < tapesCount - 1; x++) {
					this->generator.increment();
					this->machine.addTransition(this->generator.getLastState(), true, true, direction, this->generator.getCurrentState()); // 1 stays 1 (no matter the tape)
					if((direction==Machine::Direction::R && (tape + x) % tapesCount==0) || (direction==Machine::Direction::L && (tapesCount + tape - x) % tapesCount==0))
						this->machine.addTransition(this->generator.getLastState(), false, true, direction, this->generator.getCurrentState()); // 0 turns to 1 on the zeroth tape
					else
						this->machine.addTransition(this->generator.getLastState(), false, false, direction, this->generator.getCurrentState()); // 0 stays 0 on another tape
				};
				// The same for the last transition, just that the new state is the correct newState.
				this->generator.increment();
				this->machine.addTransition(this->generator.getLastState(), true, true, direction, newStatesByOldStates.at(newState));
				if((direction==Machine::Direction::R && (tape + x) % tapesCount==0) || (direction==Machine::Direction::L && (tapesCount + tape - x) % tapesCount==0))
					this->machine.addTransition(this->generator.getLastState(), false, true, direction, newStatesByOldStates.at(newState));
				else
					this->machine.addTransition(this->generator.getLastState(), false, false, direction, newStatesByOldStates.at(newState));
			};

			// If this is the first time that this state is seen, the transition for this state and the other symbol is not yet defined. This shall be noted.
			// If this is the second time that this state is seen, the previous time had to be with a transition for the other symbol.
			// machine.forEachTransition() guarantees that the transitions are ordered by the incoming states, so if this was the case, this state has to be the last one in the missingTransitions set.

			if(!missingTransitions.empty() && missingTransitions.back().first==newStatesByOldStates.at(state))
				missingTransitions.pop_back();
			else
				missingTransitions.emplace_back(newStatesByOldStates.at(state), !symbol);
		}
	);

	// this->generator.getCurrentState() shall now be the single end state to which all missing transitions are added.

	std::ranges::for_each(missingTransitions,
		[this](const std::pair<std::wstring, bool> &missingTransition) -> void {
			this->machine.addTransition(missingTransition.first, missingTransition.second, missingTransition.second, Machine::Direction::N, this->generator.getCurrentState());
		}
	);

	std::ranges::for_each(unusedStates,
		[this](const std::wstring &unusedState) -> void {
			this->addTransition<Machine::Direction::N>(unusedState, this->generator.getCurrentState());
		}
	);

	for(x = tape; x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	// Now, the machine is on the zeroth tape.
	// It has to go home, but there is one more problem to tackle.
	// The zeroth tape was only marked where the machine passed throught the cell on it.
	// That worked for the R transitions, but it is possible that the leftmost cell on the target tape that the machine visited is not accompanied by a one on the zeroth tape.
	// The parameter tape of the goHome() function ensures that this gets resolved.

	this->goHome({}, {}, tape);

	return (*this);
};

/*!
 * This method compares a number on a specified position on a specified tape with a constant.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * The behavior is undefined if the number at tape[index] does not exist (there must be strictly more numbers than index on the tape).
 * \param tape The target tape.
 * \param index The target position.
 * \param number The constant with which to compare.
 * \param lessThanState The end state if tape[index] < number.
 * \param equalState The end state if tape[index] = number.
 * \param greaterThanState The end state if tape[index] > number.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::compareWithConstant(size_t tape, size_t index, size_t number, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t tapesCount, x, y;
	std::wstring lessThanEndingState, equalEndingState, greaterThanEndingState;

	if(tape==0 || tape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	this->generator.increment();
	lessThanEndingState = this->generator.getCurrentState();

	this->findTape(tape, this->generator.getLastState(), {});

	for(x = 0; x < index; x++)
		this->skipNumber({}, {});

	this->addSuperTransition<true, true, Machine::Direction::R>({}, {}); // Skip the obligatory 0 at the beginning of the number

	for(x = 0; x < number; x++) {
		this->addTransition<false, false, Machine::Direction::N>({}, lessThanEndingState); // The number ended before the end of this loop, therefore <
		this->addTransition<true, true, Machine::Direction::R>({}, {});
		for(y = 1; y < tapesCount; y++)
			this->addTransition<Machine::Direction::R>({}, {});
	};
	equalEndingState = this->addTransition<false, false, Machine::Direction::N>({}, {}); // The number ends exactly after the loop, therefore =
	greaterThanEndingState = this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), {}); // The number ends somewhere further, therefore >

	// For all of the three options, the machine has to return to the zeroth tape and go home.

	this->addTransition<false, false, Machine::Direction::L>(lessThanEndingState, {});
	for(x = (tapesCount + tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, lessThanState);

	this->addTransition<false, false, Machine::Direction::L>(equalEndingState, {});
	for(x = (tapesCount + tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, equalState);

	this->addTransition<true, true, Machine::Direction::L>(greaterThanEndingState, {});
	for(x = (tape - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, greaterThanState);

	this->isCurrentStateDisabled = true; // Prevent regular methods using this->generator.getCurrentState() as the entrypoint

	return (*this);
};

/*!
 * Compare two numbers.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * The behavior is undefined if the numbers at tapeA[indexA] and tapeB[indexB] do not exist (there must be strictly more numbers on tapeA than indexA, the same for tapeB and indexB).
 * \param tapeA The tape on which the first number is.
 * \param tapeB The tape on which the second number is.
 * \param indexA Index of the first number.
 * \param indexB Index of the second number.
 * \param lessThanState The end state if tapeA[indexA] < tapeB[indexB].
 * \param equalState The end state if tapeA[indexA] = tapeB[indexB].
 * \param greaterThanState The end state if tapeA[indexA] > tapeB[indexB].
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::compare(size_t tapeA, size_t indexA, size_t tapeB, size_t indexB, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t tapesCount, x;
	std::wstring comparingState, skippingZerosStateA, skippingZerosStateB, lessThanOrEqualEndingState, lessThanOrEqualFillingZerosStateA, lessThanOrEqualFillingZerosStateB, greaterThanFillingZerosStateA, greaterThanFillingZerosStateB, lessThanEndingState, equalEndingState, greaterThanEndingState;

	if(tapeA==tapeB) // Use a specialized method for comparing numbers on the same tape
		return this->compare(tapeA, indexA, indexB, std::move(lessThanState), std::move(equalState), std::move(greaterThanState));

	if(tapeA==0 || tapeA > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeA.");

	if(tapeB==0 || tapeB > this->tapesCount)
		throw UnexpectedError(L"Invalid tapeB.");

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	// The beginning of the compared numbers is going to be gradually replaced with zeros to keep track of the comparison.
	// Usually, they can be reconstructed using the end of the preceding number, but if the number is the first one on the tape, it is not possible.
	// So, if this is the case, a dummy number (a 0, so a single one) will be prepended to the tape.

	if(indexA==0)
		this->addDummyZero(tapeA, {}, {});
	if(indexB==0)
		this->addDummyZero(tapeB, {}, {});

	comparingState = this->generator.getCurrentState();

	// Let us start the comparison.
	// Every iteration, a symbol will be removed from the beginning of both compared numbers.
	// std::max<size_t>(indexA, 1) and std::max<size_t>(indexB, 1) will be used as indices because of the potential prepended numbers.

	this->findTape(tapeA, comparingState, {}, false);
	for(x = 0; x < std::max<size_t>(indexA, 1); x++)
		this->skipNumber({}, {});
	skippingZerosStateA = this->generator.getCurrentState();

	// Skip potential zeros (already cleared ones).
	this->addSuperTransition<false, false, Machine::Direction::R>(skippingZerosStateA, skippingZerosStateA);
	this->addSuperTransition<true, false, Machine::Direction::R>(skippingZerosStateA, {}); // Clear a single one

	// If the cleared one was the last one, then tapeA[indexA] was definitely not the greater number.
	lessThanOrEqualEndingState = this->addTransition<false, false, Machine::Direction::N>({}, {});

	this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {});
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	this->findTape(tapeB, {}, {}, false);

	for(x = 0; x < std::max<size_t>(indexB, 1); x++)
		this->skipNumber({}, {});
	skippingZerosStateB = this->generator.getCurrentState();

	// Skip potential zeros (already cleared ones).
	this->addSuperTransition<false, false, Machine::Direction::R>(skippingZerosStateB, skippingZerosStateB);
	this->addSuperTransition<true, false, Machine::Direction::R>(skippingZerosStateB, {}); // Clear a single one

	// If the cleared one was the last one, then tapeA[indexA] was definitely the greater number.
	greaterThanEndingState = this->addTransition<false, false, Machine::Direction::N>({}, {});

	this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {});
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, comparingState);

	// This is the end of the iteration.
	// Let us sort out the ending states.
	// If in lessThanOrEqualEndingState, the machine has to check whether there is more than one symbol left of the second number.

	this->addSuperTransition<false, false, Machine::Direction::L>(lessThanOrEqualEndingState, {});
	lessThanOrEqualFillingZerosStateA = this->generator.getCurrentState();

	// Reconstruct the first number.
	this->addSuperTransition<false, true, Machine::Direction::L>(lessThanOrEqualFillingZerosStateA, lessThanOrEqualFillingZerosStateA);
	this->addSuperTransition<true, true, Machine::Direction::R>(lessThanOrEqualFillingZerosStateA, {});

	this->addTransition<true, false, Machine::Direction::L>({}, {});
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	this->findTape(tapeB, {}, {});
	for(x = 0; x < std::max<size_t>(indexB, 1); x++)
		this->skipNumber({}, {});

	// Reconstruct the second number.
	lessThanOrEqualFillingZerosStateB = this->generator.getCurrentState();
	this->addSuperTransition<false, true, Machine::Direction::R>(lessThanOrEqualFillingZerosStateB, lessThanOrEqualFillingZerosStateB);
	this->addSuperTransition<true, true, Machine::Direction::R>(lessThanOrEqualFillingZerosStateB, {});

	equalEndingState = this->addTransition<false, false, Machine::Direction::N>({}, {}); // There was only one one left
	lessThanEndingState = this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), {}); // There is another one.

	// Return home from equalEndingState and lessThanEndingState.

	this->addTransition<false, false, Machine::Direction::L>(equalEndingState, {});
	for(x = (tapesCount + tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	if(indexA==0)
		this->removeDummyZero(tapeA, {}, {});
	if(indexB==0)
		this->removeDummyZero(tapeB, {}, {});
	this->addTransition<true, true, Machine::Direction::N>({}, equalState);

	this->addTransition<true, true, Machine::Direction::L>(lessThanEndingState, {});
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	if(indexA==0)
		this->removeDummyZero(tapeA, {}, {});
	if(indexB==0)
		this->removeDummyZero(tapeB, {}, {});
	this->addTransition<true, true, Machine::Direction::N>({}, lessThanState);

	this->addSuperTransition<false, false, Machine::Direction::L>(greaterThanEndingState, {});

	// If the second number is discovered to be smaller, the result is already clear, but both numbers still have to be reconstructed.

	greaterThanFillingZerosStateB = this->generator.getCurrentState();
	this->addSuperTransition<false, true, Machine::Direction::L>(greaterThanFillingZerosStateB, greaterThanFillingZerosStateB);
	this->addSuperTransition<true, true, Machine::Direction::R>(greaterThanFillingZerosStateB, {});

	this->addTransition<true, false, Machine::Direction::L>({}, {});
	for(x = (tapeB - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, {});

	this->findTape(tapeA, {}, {});
	for(x = 0; x < std::max<size_t>(indexA, 1); x++)
		this->skipNumber({}, {});

	greaterThanFillingZerosStateA = this->generator.getCurrentState();
	this->addSuperTransition<false, true, Machine::Direction::R>(greaterThanFillingZerosStateA, greaterThanFillingZerosStateA);
	this->addTransition<true, true, Machine::Direction::L>(greaterThanFillingZerosStateA, {});
	for(x = (tapeA - 1); x > 0; x--)
		this->addTransition<Machine::Direction::L>({}, {});

	this->goHome({}, {});
	if(indexA==0)
		this->removeDummyZero(tapeA, {}, {});
	if(indexB==0)
		this->removeDummyZero(tapeB, {}, {});
	this->addTransition<true, true, Machine::Direction::N>({}, greaterThanState);

	this->isCurrentStateDisabled = true; // Prevent the next method from using the current state as the start state

	return (*this);
};

/*!
 * Compare two numbers on the same tape.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * The behavior is undefined if the numbers at tape[indexA] and tape[indexB] do not exist (there must be strictly more numbers than max({ indexA; indexB }) on the tape).
 * \param tape The tape on which the two numbers are.
 * \param indexA Index of the first number.
 * \param indexB Index of the second number.
 * \param lessThanState The end state if tape[indexA] < tape[indexB].
 * \param equalState The end state if tape[indexA] = tape[indexB].
 * \param greaterThanState The end state if tape[indexA] > tape[indexB].
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::compare(size_t tape, size_t indexA, size_t indexB, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	bool isInitialStateAssigned = false;
	size_t tapesCount;
	std::vector<std::wstring> singleTapeMachineExtraStates;
	std::map<std::wstring, std::wstring> newStatesByOldStates;
	Machine singleTapeMachine;
	SingleTapeMachineFactory singleTapeMachineFactory;

	if(tape==0 || tape > this->tapesCount)
		throw UnexpectedError(L"Invalid tape.");

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	// If the indices are equal, then the numbers are equal as well.
	// The machine will just jump to equalState in that case.

	if(indexA==indexB) {
		this->addTransition<true, true, Machine::Direction::N>({}, equalState);
		this->isCurrentStateDisabled = true; // Prevent the next called method from using the current state as the start state

		return (*this);
	};

	tapesCount = (this->tapesCount + 1);

	this->findTape(tape, {}, {});

	// The comparison itself is delegated to SingleTapeMachineFactory::compare().
	// The machine is at the correct tape now, so the machine created by the SingleTapeMachineFactory can be adopted.
	// This does practically the same as MultiTapeMachineFactory::adopt(), but cares about the three end states.

	singleTapeMachineExtraStates = singleTapeMachineFactory.createExtraStates(3);
	singleTapeMachineFactory.compare(indexA, indexB, singleTapeMachineExtraStates[0], singleTapeMachineExtraStates[1], singleTapeMachineExtraStates[2]);
	singleTapeMachineFactory.extractMachine().forEachTransition(
		[this, &newStatesByOldStates, &isInitialStateAssigned, tapesCount](const std::wstring &state, bool symbol, bool newSymbol, Machine::Direction direction, const std::wstring &newState) -> void {
			size_t x;

			if(!std::exchange(isInitialStateAssigned, true)) // This is the first adopted transition, so it begins the start state of the single-tape machine and should be connected to the current state of the multi-tape machine
				newStatesByOldStates.emplace(state, this->generator.getCurrentState());
			else if(!newStatesByOldStates.contains(state)) { // A not yet seen incoming state
				this->generator.increment();
				newStatesByOldStates.emplace(state, this->generator.getCurrentState());
			};

			if(!newStatesByOldStates.contains(newState)) { // A not yet seen outgoing state
				this->generator.increment();
				newStatesByOldStates.emplace(newState, this->generator.getCurrentState());
			};

			if(direction==Machine::Direction::N) // A N-transition is simple to adopt, just add a N-transition
				this->machine.addTransition(newStatesByOldStates.at(state), symbol, newSymbol, direction, newStatesByOldStates.at(newState));
			else { // A L- or R-transition is simulated by moving to the neighboring cell of the same virtual tape
				this->generator.increment();
				this->machine.addTransition(newStatesByOldStates.at(state), symbol, newSymbol, direction, this->generator.getCurrentState());
				for(x = 1; x < tapesCount - 1; x++) {
					this->generator.increment();
					this->machine.addTransition(this->generator.getLastState(), true, true, direction, this->generator.getCurrentState());
					this->machine.addTransition(this->generator.getLastState(), false, false, direction, this->generator.getCurrentState());
				};
				this->machine.addTransition(this->generator.getCurrentState(), true, true, direction, newStatesByOldStates.at(newState));
				this->machine.addTransition(this->generator.getCurrentState(), false, false, direction, newStatesByOldStates.at(newState));
			};
		}
	);

	// Now, the machine should end up in newStatesByOldStates.at(singleTapeMachineExtraState[0]), newStatesByOldStates.at(singleTapeMachineExtraState[1]) or newStatesByOldStates.at(singleTapeMachineExtraState[2]).
	// For each of those states, the machine has to return to the beginning.

	std::ranges::for_each(std::initializer_list<std::pair<size_t, std::wstring>> { { 0, lessThanState }, { 1, equalState }, { 2, greaterThanState } },
		[this, &singleTapeMachineExtraStates, &newStatesByOldStates, tape](const std::pair<size_t, std::wstring> &states) -> void {
			size_t singleTapeMachineExtraState, x;
			std::wstring multiTapeMachineState;

			std::tie(singleTapeMachineExtraState, multiTapeMachineState) = std::move(states);

			this->addTransition<true, true, Machine::Direction::L>(newStatesByOldStates.at(singleTapeMachineExtraStates[singleTapeMachineExtraState]), {});
			for(x = (tape - 1); x > 0; x--)
				this->addTransition<Machine::Direction::L>({}, {});
			this->goHome({}, multiTapeMachineState);
		}
	);

	this->isCurrentStateDisabled = true; // Prevent the next called method from using the current state as the start state

	return (*this);
};

/*!
 * Count the numbers on a tape and compare it with a constant.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * \param tape The tape to count.
 * \param number The number with which to compare.
 * \param lessThanState The end state if |tape| < number.
 * \param equalState The end state if |tape| = number.
 * \param greaterThanState The end state if |tape| > number.
 */
MultiTapeMachineFactory &MultiTapeMachineFactory::compareTapeLength(size_t tape, size_t number, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t tapesCount, x;
	std::wstring startState, lessThanEndingState, equalEndingState, greaterThanEndingState, comparingState;

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	tapesCount = (this->tapesCount + 1);

	startState = this->generator.getCurrentState();

	if(number > 0) {
		this->generator.increment();
		lessThanEndingState = this->generator.getCurrentState();
	};

	this->generator.increment();
	equalEndingState = this->generator.getCurrentState();

	this->generator.increment();
	greaterThanEndingState = this->generator.getCurrentState();

	this->findTape(tape, startState, {});

	for(x = 0; x < number; x++) {
		comparingState = this->generator.getCurrentState();
		if(x==0)
			this->addTransition<false, false, Machine::Direction::N>(comparingState, lessThanEndingState); // Zero where the beginning of the next number is expected
		else {
			this->addSuperTransition<false, false, Machine::Direction::L>({}, {}); // Zero where the beginning of the next number is expected
			this->addSuperTransition<false, false, Machine::Direction::L>({}, lessThanEndingState); // This should be in the valid range, so goHome should work
		};
		this->addTransition<true, true, Machine::Direction::N>(comparingState, {}); // The beginning of the next number
		this->skipNumber({}, {});
	};

	this->addTransition<false, false, Machine::Direction::N>({}, equalEndingState);
	this->addTransition<true, true, Machine::Direction::N>({}, greaterThanEndingState);

	if(number > 0) {
		this->addTransition<Machine::Direction::L>(lessThanEndingState, {});
		for(x = (tape - 1); x > 0; x--) // Return to the zeroth tape
			this->addTransition<Machine::Direction::L>({}, {});
		this->goHome({}, lessThanState);
	};

	this->addTransition<false, false, Machine::Direction::L>(equalEndingState, {});
	for(x = ((number==0) ? (tape - 1) : (tapesCount * 2 + tape - 1)); x > 0; x--) // Return to the zeroth tape
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, equalState);

	this->addTransition<true, true, Machine::Direction::L>(greaterThanEndingState, {});
	for(x = (tape - 1); x > 0; x--) // Return to the zeroth tape
		this->addTransition<Machine::Direction::L>({}, {});
	this->goHome({}, greaterThanState);

	this->isCurrentStateDisabled = true;

	return (*this);
};
