#include "./singleTapeMachineFactory.hpp"
#include "../IO/unexpectedError.hpp"

/*!
 * This method goes to the first 1 on the tape.
 * \param returningState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 */
std::wstring SingleTapeMachineFactory::goHome(std::optional<std::wstring> returningState, std::optional<std::wstring> endState) {
	if(!returningState)
		returningState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::L>(returningState);
	this->addTransition<false, false, Machine::Direction::L>(returningState, {});
	this->addTransition<true, true, Machine::Direction::L>({}, returningState);
	this->addTransition<false, false, Machine::Direction::R>({}, {});
	endState = this->addTransition<false, false, Machine::Direction::R>({}, endState);

	return (*endState);
};

/*!
 * This method finds the end of the tape.
 * It expects the machine to be at the beginning of a number on the tape.
 * \param findingEndState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one when the call of this method ends).
 */
std::wstring SingleTapeMachineFactory::findEnd(std::optional<std::wstring> findingEndState, std::optional<std::wstring> endState) {
	if(!findingEndState)
		findingEndState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::R>(findingEndState);
	this->addTransition<false, false, Machine::Direction::R>(findingEndState, {});
	this->addTransition<true, true, Machine::Direction::R>({}, findingEndState);
	endState = this->addTransition<false, false, Machine::Direction::N>({}, {});

	return (*endState);
};

/*!
 * This method skips one number on the tape.
 * \tparam direction Direction of the skipping (left or right).
 * \param skippingState The start state, if {}, then the current state of the state generator.
 * \param endState The end state, if {}, then a new state generated by the generator (which will be the current one after the method ends).
 */
template<Machine::Direction direction>
	std::wstring SingleTapeMachineFactory::skipNumber(std::optional<std::wstring> skippingState, std::optional<std::wstring> endState) {
		if(!skippingState)
			skippingState = this->generator.getCurrentState();

		this->addTransition<true, true, direction>(skippingState);
		endState = this->addTransition<false, false, direction>(skippingState, endState);

		return (*endState);
	};

/*!
 * Compare two adjacent numbers on the tape.
 * The machine has to be at the beginning of the first number.
 * \param lessThanState End state if the second number is greater.
 * \param equalState End state if the numbers are equal.
 * \param greaterThanState End state if the first number is greater.
 */
void SingleTapeMachineFactory::compareAdjacentNumbers(std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	std::wstring comparingState, lessThanOrEqualEndingState, greaterThanEndingState, lessThanEndingState, equalEndingState;

	// Find the end of the first number.
	this->addTransition<true, true, Machine::Direction::R>({});
	comparingState = this->addTransition<false, true, Machine::Direction::L>({}, {}); // Change the number separator from 0 to 1

	this->addTransition<true, false, Machine::Direction::L>({}, {}); // Clear the 1 at the end
	lessThanOrEqualEndingState = this->addTransition<false, false, Machine::Direction::R>({}, {}); // It was the last remainding 1, so the first number cannot have been greater that the second number
	this->addTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), {}); // It was not the last remainding 1
	this->addTransition<false, false, Machine::Direction::R>({}); // Find the separator between the two numbers
	this->addTransition<true, true, Machine::Direction::R>({}, {});

	this->addTransition<false, false, Machine::Direction::R>({}); // Skip the cleared out part of the second number
	this->addTransition<true, false, Machine::Direction::R>({}, {}); // Clear the next 1
	greaterThanEndingState = this->addTransition<false, false, Machine::Direction::L>({}, {}); // It was the last remainding 1, so the second number cannot have been greater than the first number
	this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {}); // It was not the last remainding 1
	this->addTransition<false, false, Machine::Direction::L>({}); // Find the separator between the two numbers
	this->addTransition<true, true, Machine::Direction::L>({}, {});

	this->addTransition<false, false, Machine::Direction::L>({}); // Skip the cleared out part of the first number
	this->addTransition<true, true, Machine::Direction::N>({}, comparingState);

	// The iteration is over now.
	// Let us sort out the ending states.

	this->addTransition<false, true, Machine::Direction::R>(lessThanOrEqualEndingState); // Reconstruct the first number
	this->addTransition<true, false, Machine::Direction::R>(lessThanOrEqualEndingState, {}); // Change the separator back to 0
	this->addTransition<false, true, Machine::Direction::R>({}); // Reconstruct the second number
	this->addTransition<true, true, Machine::Direction::R>({}, {});
	equalEndingState = this->addTransition<false, false, Machine::Direction::L>({}, {}); // There was exactly one 1 remaining, so the numbers were equal
	lessThanEndingState = this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {}); // There was more than one 1 remainding, so the second number was greater

	this->goHome(lessThanEndingState, lessThanState);
	this->goHome(equalEndingState, equalState);

	this->addTransition<false, true, Machine::Direction::L>(greaterThanEndingState); // Reconstruct the second number
	this->addTransition<true, false, Machine::Direction::L>(greaterThanEndingState, {}); // Change the separator back to 0
	this->addTransition<false, true, Machine::Direction::L>({}); // Reconstruct the first number
	this->addTransition<true, true, Machine::Direction::N>({}, {});
	this->goHome({}, greaterThanState);
};

/*!
 * Compare two numbers on the tape.
 * The second number has to be right of the first number.
 * The machine has to be at the beginning of the first number.
 * \param distance The distance between the two numbers, has to be greater than 0. 1 means adjacent.
 * \param lessThanState End state if the second number is greater.
 * \param equalState End state if the numbers are equal.
 * \param greaterThanState End state if the first number is greater.
 */
void SingleTapeMachineFactory::compare(size_t distance, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t x;
	std::wstring comparingState, lessThanOrEqualEndingState, greaterThanEndingState, lessThanEndingState, equalEndingState;

	// The case where the second number is directly behind the first will be handled separately.
	if(distance==1)
		return this->compareAdjacentNumbers(std::move(lessThanState), std::move(equalState), std::move(greaterThanState));

	// Find the end of the first number.
	this->addTransition<true, true, Machine::Direction::R>({});
	comparingState = this->addTransition<false, false, Machine::Direction::L>({}, {});

	this->addTransition<true, false, Machine::Direction::L>(comparingState, {}); // Clear the 1 at the end
	lessThanOrEqualEndingState = this->addTransition<false, false, Machine::Direction::R>({}, {}); // It was the last remainding 1, so the first number cannot have been greater that the second number
	this->addTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), {}); // It was not the last remainding 1
	this->addTransition<false, false, Machine::Direction::R>({}); // Skip to the next number
	this->addTransition<true, true, Machine::Direction::N>({}, {});
	for(x = 1; x < distance; x++)
		this->skipNumber({}, {});

	this->addTransition<false, false, Machine::Direction::R>({}); // Skip the cleared out part of the second number
	this->addTransition<true, false, Machine::Direction::R>({}, {}); // Clear the next 1
	greaterThanEndingState = this->addTransition<false, false, Machine::Direction::L>({}, {}); // It was the last remainding 1, so the second number cannot have been greater than the first number
	this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {}); // It was not the last remainding 1
	this->addTransition<false, false, Machine::Direction::L>({}); // Skip to the previous number
	this->addTransition<true, true, Machine::Direction::N>({}, {});
	for(x = (distance - 1); x > 0; x--)
		this->skipNumber<Machine::Direction::L>({}, {});

	this->addTransition<false, false, Machine::Direction::L>({}); // Skip the cleared out part of the first number
	this->addTransition<true, true, Machine::Direction::N>({}, comparingState);

	// The iteration is over now.
	// Let us sort out the ending states.

	this->addTransition<false, true, Machine::Direction::R>(lessThanOrEqualEndingState); // Reconstruct the first number
	this->addTransition<true, true, Machine::Direction::L>(lessThanOrEqualEndingState, {});
	this->addTransition<true, false, Machine::Direction::R>({}, {}); // Repair the space between numbers
	for(x = 1; x < distance; x++)
		this->skipNumber({}, {});

	this->addTransition<false, true, Machine::Direction::R>({}); // Reconstruct the second number
	this->addTransition<true, true, Machine::Direction::R>({}, {});
	equalEndingState = this->addTransition<false, false, Machine::Direction::L>({}, {}); // There was exactly one 1 remaining, so the numbers were equal
	lessThanEndingState = this->addTransition<true, true, Machine::Direction::L>(this->generator.getLastState(), {}); // There was more than one 1 remainding, so the second number was greater

	this->goHome(lessThanEndingState, lessThanState);
	this->goHome(equalEndingState, equalState);

	this->addTransition<false, true, Machine::Direction::L>(greaterThanEndingState); // Reconstruct the second number
	this->addTransition<true, true, Machine::Direction::R>(greaterThanEndingState, {});
	this->addTransition<true, false, Machine::Direction::L>({}, {}); // Repair the space between numbers
	for(x = (distance - 1); x > 0; x--)
		this->skipNumber<Machine::Direction::L>({}, {});

	this->addTransition<false, true, Machine::Direction::L>({}); // Reconstruct the first number
	this->addTransition<true, true, Machine::Direction::N>({}, {});
	this->goHome({}, greaterThanState);
};

/*!
 * This method clears numbers from the beginning of a tape.
 * The behavior is undefined if there is not enough numbers on the tape (less than count).
 * \param count How many numbers to clear.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::clearBeginning(size_t count) {
	size_t x;

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	for(x = 0; x < count; x++) {
		this->addTransition<true, false, Machine::Direction::R>({});
		this->addTransition<false, false, Machine::Direction::R>({}, {});
	};

	return (*this);
};

/*!
 * This method clears numbers from the end of a tape.
 * The behavior is undefined if there is not enough numbers on the tape (less than begin).
 * \param begin From where to clear (how many numbers to keep).
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::clearEnd(size_t begin) {
	size_t x;

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	for(x = 0; x < begin; x++)
		this->skipNumber({}, {});

	this->addTransition<true, false, Machine::Direction::R>({});
	this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<true, false, Machine::Direction::R>({}, this->generator.getLastState());

	if(begin==0)
		this->addTransition<false, false, Machine::Direction::L>({}, {});
	else {
		this->addTransition<false, false, Machine::Direction::L>({}, {});
		this->addTransition<false, false, Machine::Direction::L>({});
		this->addTransition<true, true, Machine::Direction::N>({}, {});
		this->goHome({}, {});
	};

	return (*this);
};

/*!
 * This method writes a number (n + 1 ones after one zero) somewhere on a tape.
 * If there is something more on the tape behind the target position, it gets deleted.
 * The behavior is undefined if there is not enough numbers on the tape (less than begin).
 * \param begin The target position (0 is the beginning).
 * \param number The number to be written.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::writeNumber(size_t begin, size_t number) {
	size_t x;

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	for(x = 0; x < begin; x++)
		this->skipNumber({}, {});

	for(x = 0; x <= number; x++) {
		this->addTransition<false, true, Machine::Direction::R>({}, {});
		this->addTransition<true, true, Machine::Direction::R>(this->generator.getLastState(), this->generator.getCurrentState());
	};

	this->addTransition<true, false, Machine::Direction::R>({});
	this->addTransition<false, false, Machine::Direction::R>({}, {});
	this->addTransition<true, false, Machine::Direction::R>({}, this->generator.getLastState());

	this->addTransition<false, false, Machine::Direction::L>({}, {});
	this->addTransition<false, false, Machine::Direction::L>({});
	this->addTransition<true, true, Machine::Direction::N>({}, {});

	this->goHome({}, {});

	return (*this);
};

/*!
 * This method writes a number (n + 1 ones after one zero) behind the last number.
 * If the tape is empty, it writes it on a valid position.
 * \param number The number to be written.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::appendNumber(size_t number) {
	size_t x;

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	this->findEnd({}, {});

	for(x = 0; x <= number; x++)
		this->addTransition<false, true, Machine::Direction::R>({}, {});

	this->goHome({}, {});

	return (*this);
};

/*!
 * This method accepts a Turing machine which will be simulated on the tape.
 * The simulated machine is expected to end with a valid state of the tape.
 * \param machine The Turing machine.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::simulate(const Machine &machine) {
	std::vector<std::pair<std::wstring, bool>> missingTransitions;
	std::set<std::wstring> unusedStates;
	std::map<std::wstring, std::wstring> newStatesByOldStates;

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	machine.forEachTransition(
		[this, &unusedStates, &missingTransitions, &newStatesByOldStates](const std::wstring &state, bool symbol, bool newSymbol, Machine::Direction direction, const std::wstring &newState) -> void {
			if(!newStatesByOldStates.contains(state)) {
				newStatesByOldStates.emplace(state, this->generator.getCurrentState());
				this->generator.increment();
			}
			else
				unusedStates.erase(newStatesByOldStates.at(state));

			if(!newStatesByOldStates.contains(newState)) {
				newStatesByOldStates.emplace(newState, this->generator.getCurrentState());
				unusedStates.insert(this->generator.getCurrentState());
				this->generator.increment();
			};

			this->machine.addTransition(newStatesByOldStates.at(state), symbol, newSymbol, direction, newStatesByOldStates.at(newState));

			if(!missingTransitions.empty() && missingTransitions.back().first==newStatesByOldStates.at(state))
				missingTransitions.pop_back();
			else
				missingTransitions.emplace_back(newStatesByOldStates.at(state), !symbol);
		}
	);

	std::ranges::for_each(missingTransitions,
		[this](const std::pair<std::wstring, bool> &missingTransition) -> void {
			this->machine.addTransition(missingTransition.first, missingTransition.second, missingTransition.second, Machine::Direction::N, this->generator.getCurrentState());
		}
	);

	std::ranges::for_each(unusedStates,
		[this](const std::wstring &unusedState) -> void {
			this->addTransition<Machine::Direction::N>(unusedState, this->generator.getCurrentState());
		}
	);

	return (*this);
};

/*!
 * This method compares a number on a specified position on the tape with a constant.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * The behavior is undefined if the number at the does not exist (there must be strictly more numbers than index on the tape).
 * \param index The target position.
 * \param number The constant with which to compare.
 * \param lessThanState The end state if tape[index] < number.
 * \param equalState The end state if tape[index] = number.
 * \param greaterThanState The end state if tape[index] > number.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::compareWithConstant(size_t index, size_t number, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t x;
	std::wstring lessThanEndingState, equalEndingState, greaterThanEndingState;

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	this->generator.increment();
	lessThanEndingState = this->generator.getCurrentState();

	this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), {});

	for(x = 0; x < index; x++)
		this->skipNumber({}, {});

	this->addTransition<true, true, Machine::Direction::R>({}, {});
	for(x = 0; x < number; x++) {
		this->addTransition<false, false, Machine::Direction::N>({}, lessThanEndingState);
		this->addTransition<true, true, Machine::Direction::R>({}, {});
	};
	equalEndingState = this->addTransition<false, false, Machine::Direction::N>({}, {});
	greaterThanEndingState = this->addTransition<true, true, Machine::Direction::N>(this->generator.getLastState(), {});

	this->addTransition<false, false, Machine::Direction::L>(lessThanEndingState, {});
	this->goHome({}, lessThanState);

	this->addTransition<false, false, Machine::Direction::L>(equalEndingState, {});
	this->goHome({}, equalState);

	this->addTransition<true, true, Machine::Direction::L>(greaterThanEndingState, {});
	this->goHome({}, greaterThanState);

	this->isCurrentStateDisabled = true;

	return (*this);
};

/*!
 * Compare two numbers on the tape.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * The behavior is undefined if the numbers at indexA and indexB do not exist (there must be strictly more numbers than max({ indexA; indexB }) on the tape).
 * \param indexA Index of the first number.
 * \param indexB Index of the second number.
 * \param lessThanState The end state if the number at indexB is greater.
 * \param equalState The end state if the numbers are equal.
 * \param greaterThanState The end state if the number at indexA is greater.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::compare(size_t indexA, size_t indexB, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t x;

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	// If the indices are equal, then the numbers are equal as well.
	// The machine will just jump to equalState in that case.

	if(indexA==indexB) {
		this->addTransition<true, true, Machine::Direction::N>({}, equalState);
		this->isCurrentStateDisabled = true; // Prevent the next called method from using the current state as the start state

		return (*this);
	};

	// Without loss of generality, indexA < indexB.
	// If it is not the case, the indices and end states will be swapped.

	if(indexA > indexB) {
		std::swap(indexA, indexB);
		std::swap(lessThanState, greaterThanState);
	};

	for(x = 0; x < indexA; x++)
		this->skipNumber({}, {});

	this->compare(indexB - indexA, std::move(lessThanState), std::move(equalState), std::move(greaterThanState));

	this->isCurrentStateDisabled = true;

	return (*this);
};

/*!
 * Count the numbers on the tape and compare it with a constant.
 * Depending on the result of the comparison, the machine ends up in lessThanState, equalState or greaterThanState.
 * Those states have to be created beforehand with createExtraStates().
 * No function depending on the current state can be called after compareWithConstant, addNTransition has to be next.
 * \param number The number with which to compare.
 * \param lessThanState The end state if |tape| < number.
 * \param equalState The end state if |tape| = number.
 * \param greaterThanState The end state if |tape| > number.
 */
SingleTapeMachineFactory &SingleTapeMachineFactory::compareTapeLength(size_t number, std::wstring lessThanState, std::wstring equalState, std::wstring greaterThanState) {
	size_t x;
	std::wstring startState, lessThanEndingState, equalEndingState, greaterThanEndingState;

	if(!this->extraStates.contains(lessThanState) || !this->extraStates.contains(equalState) || !this->extraStates.contains(greaterThanState))
		throw UnexpectedError(L"States given to the machine factory must be extra states.");

	if(this->isCurrentStateDisabled)
		throw UnexpectedError(L"Current state is disabled.");

	startState = this->generator.getCurrentState();

	if(number > 0) {
		this->generator.increment();
		lessThanEndingState = this->generator.getCurrentState();

		this->generator.increment();
		equalEndingState = this->generator.getCurrentState();

		this->generator.increment();
		greaterThanEndingState = this->generator.getCurrentState();
	};

	this->addTransition<Machine::Direction::N>(startState, {});
	for(x = 0; x < number; x++) {
		this->addTransition<false, false, Machine::Direction::N>({}, (x==0) ? lessThanState : lessThanEndingState); // Zero where the beginning of the next number is expected
		this->addTransition<true, true, Machine::Direction::N>({}, {}); // The beginning of the next number
		this->skipNumber({}, {});
	};

	this->addTransition<false, false, Machine::Direction::N>({}, (x==0) ? equalState : equalEndingState);
	this->addTransition<true, true, Machine::Direction::N>({}, (x==0) ? greaterThanState : greaterThanEndingState);

	if(number > 0) {
		this->addTransition<false, false, Machine::Direction::L>(lessThanEndingState, {}); // Necessary, so that goHome() doesn’t think that we are already at the start
		this->goHome({}, lessThanState);
		this->addTransition<false, false, Machine::Direction::L>(equalEndingState, {}); // Necessary, so that goHome() doesn’t think that we are already at the start
		this->goHome({}, equalState);
		this->goHome(greaterThanEndingState, greaterThanState);
	};

	this->isCurrentStateDisabled = true;

	return (*this);
};
